### PR TITLE
Added missing options ajaxBase and ajaxCredentials

### PR DESCRIPTION
**Pull request by pmk65**
Added documentation on 2 "hidden" features.
See https://github.com/json-editor/json-editor/issues/367

### CODE REVIEW

**Comment by schmunk42** [comment]
How are *credentials* used, BASIC_AUTH?

**Comment by pmk65** [comment]
> 
> 
> How are _credentials_ used, BASIC_AUTH?

It set [withCredentials](url) to the value of `ajaxCredentials`
See: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by schmunk42** [comment]
I tried to add the link in the description, but apparently it does not work in `tr` `td`s ... should we just add the URL?

**Comment by pmk65** [comment]
> 
> 
> I tried to add the link in the description, but apparently it does not work in `tr` `td`s ... should we just add the URL?

I'm not sure what you mean about tr td? These shouldn't affect the display.

**Comment by schmunk42** [comment]
Hmm, not a big issue, but ... https://github.com/json-editor/json-editor#options

It should look like this

[credentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials)

**Pull request merged**
