### PR TITLE
Sirockin fix defaults

### PR DESCRIPTION
**Pull request by pmk65**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by sirockin** [comment]
I'm confused here. The PR lists a lot of changes but most of these are in #499. Can't you submit your changes as part of the review to #499?

**Comment by pmk65** [comment]
I tried, but my branch is currently messed up due to all the unmerged PRs I have to merge in locally.
Would be great if we could get the develop/2.x branch up-to-date with all the unmerged PRs.

**Comment by sirockin** [comment]
Can't you just edit this PR (pulling locally first if necessary) then update directly?

**Comment by pmk65** [comment]
I'll probably make a clean PR with updated tests. (I have fixed the problems with the Buttons test too)

**Comment by sirockin** [comment]
What was the problem with the button tests? I'm not sure we should edit them since they were working against the gulp build and I'd prefer we find out what has changed to break them.

**Comment by pmk65** [comment]
one of the problem was the checks for "disabled" which didn't produce the expected results. 
In changed those to `I.seeElement('[data-schemapath="root.button2"] button:disabled');` and `I.seeElement('[data-schemapath="root.button2"] button:not(:disabled)');` which does work.

Also then the "onchange" even was not triggered before testing for ":not(:disabled)", so I had to insert a dummy value to trigger the focus/blur event.

Puppeteer makes it very easy to create tests, so I'm going to make some more for the other 2.x features I have implemented. 😉

**Comment by sirockin** [comment]
So why was the test working against the old build?

**Comment by sirockin** [comment]
Anyway if you've submitted changes as a new PR, I suggest you approve this one so we can merge it.

**Comment by pmk65** [comment]
Dunno. They shouldn't have worked. As getting the disabled attribute will not return a true/false value.
I found alternate method of using `I.seeElement` in a codeceptjs thread where someone had the same plroblem.

**Comment by pmk65** [comment]
> 
> 
> Anyway if you've submitted changes as a new PR, I suggest you approve this one so we can merge it.

You can review/approve it, but not me. As it was me who submitted the PR. 😁

**Comment by sirockin** [comment]
> Anyway if you've submitted changes as a new PR, I suggest you approve this one so we can merge it.
Yes sorry I just realised I'm commenting on your new PR. Okay I'll merge my old one.

**Pull request merged**
