### PR TITLE
Improvements to array change events.

### PR DESCRIPTION
**Pull request by jramstedt**
Copying array items didn't send events, now they do.
Array events now include added/removed/moved editor as first argument.

### CODE REVIEW

**Comment by pmk65** [comment]
`tests/codeceptjs/editors/array_test.js` needs to be updated to match the new parameters.

**Comment by schmunk42** [comment]
@jramstedt I fixed the missing semicolon, but the tests don't pass.

**Comment by jramstedt** [comment]
The test is correct. There shouldn't be need to empty the editor before setting new value.

**Comment by pmk65** [comment]
I'm not sure what is is I have to review. @jramstedt Do you have a test case?

**Comment by jramstedt** [comment]
I can try to make a new test case (or add event listeners to existing one) when I have more time.

**Comment by germanbisurgi** [comment]
LGTM. Its a nice feature :)

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
