### PR TITLE
Update README_ADDON.md

### PR DESCRIPTION
**Pull request by pmk65**
- Added list of options for each 2.x Theme

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by pmk65** [comment]
The test seem buggy. It shouldn't fail on any tests since this is just an update to the readme files.

**Comment by schmunk42** [comment]
> The test seem buggy. It shouldn't fail on any tests since this is just an update to the readme files.

I have a hardening-tests brach which might help here. (Firefox is restarting the browser all the time, which takes much longer and tends to esoteric issues.

**Comment by pmk65** [comment]
@schmunk42 Do we really need to test BOTH the minified and unminified versions in BOTH browsers?
It seems like a waste of time.

**Comment by schmunk42** [comment]
> @schmunk42 Do we really need to test BOTH the minified and unminified versions in BOTH browsers?
> It seems like a waste of time.

This usually runs in parallel.

**Pull request merged**
