### PR TITLE
Fix of #408

### PR DESCRIPTION
**Pull request by pmk65**
Fixes problem with upload editor (Was actually the new "describedBy" editor that caused the problems.)

### CODE REVIEW

**Comment by schmunk42** [comment]
@germanbisurgi Could you add a test on top of this PR.

**Comment by pmk65** [comment]
> 
> 
> @germanbisurgi Could you add a test on top of this PR.

Not sure a test will help. As this was a programming error (checked for property before ensuring object existed)

**Comment by schmunk42** [comment]
Wasn't the editor not visible at all? I'd at least do this basic check.

**Comment by pmk65** [comment]
> 
> 
> Wasn't the editor not visible at all? I'd at least do this basic check.

It failed due to an error, so nothing was displayed.

**Comment by pmk65** [comment]
@schmunk42 we should probably merge this, so that the upload editor is working again.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
