### PR TITLE
Update Tailwind to Develop/2.x

### PR DESCRIPTION
**Pull request by mirannda**
Upgrade tailwind to version 2.0

### CODE REVIEW

**Comment by mirannda** [comment]
@schmunk42  
It was wrong again ... close again sorry ... I will send in a comment.

**Comment by pmk65** [comment]
> 
> 
> @schmunk42
> It was wrong again ... close again sorry ... I will send in a comment.

I made the same mistakes when I submitted my first PR 😁 
The 'trick' is to only add/commit the files you want to submit.

**Comment by mirannda** [comment]
Is True, but I will learn, I installed the git desktop and made a commit
there ... I think it did not receive ... we have a habit of ignoring a
little simple things, such as Git, I need to dig deeper, Thank you for
understanding.

Em qua, 14 de ago de 2019 às 12:23, Peter Klein <notifications@github.com>
escreveu:

**Comment by pmk65** [comment]
@mirannda A quick way to fix it (without having to to resort to various git commands,

1) Take a copy of your Tailwind files and save them in another folder.
2) Delete the entire develop/2.x branch from your computer.
3) Clone the develop/2.x branch again, so you have a clean version.
4) Move your Tailwind files back into the new develop/2.x branch
5) Do a `git status` (There should only your Tailwind files in the list of changed filed)
6) Add and commit the Tailwind files, and then push.

**Comment by mirannda** [comment]
PS D:\git\json-editor\src\themes> git push
remote: Permission to json-editor/json-editor.git denied to mirannda.
fatal: unable to access 'https://github.com/json-editor/json-editor.git/':
The requested URL returned error: 403



Em qua, 14 de ago de 2019 às 13:17, Peter Klein <notifications@github.com>
escreveu:

**Comment by pmk65** [comment]
Ahh. You might not have access to push directly to the develop/2.x branch. Try this:

1) Take a copy of your Tailwind files and save them in another folder.
2) Delete the entire develop/2.x branch from your computer.
3) Clone the develop/2.x branch again, so you have a clean version.
4) `git branch develop/2.x` (This should put you into the develop/2.x branch. Use `git branch` to check if you are on the correct branch)
5) `git checkout -B tailwind2.x` (this will create a new branch based on the branch you are on now (develop/2.x) and put you on the branch)
6) Move your Tailwind files back into the new tailwind2.x branch
7) Do a `git status` (There should only your Tailwind files in the list of changed filed)
8) Add and commit the Tailwind files, and then push.
9) Follow the instructions on how to push it to the repo.

**Comment by mirannda** [comment]
Almir@PC-Miro MINGW64 /d/git (master)
$ git clone git@github.com:json-editor/json-editor.git
Cloning into 'json-editor'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 6380 (delta 5), reused 11 (delta 5), pack-reused 6363
Receiving objects: 100% (6380/6380), 4.12 MiB | 3.26 MiB/s, done.
Resolving deltas: 100% (4660/4660), done.

Almir@PC-Miro MINGW64 /d/git (master)
$ cd json-editor/

Almir@PC-Miro MINGW64 /d/git/json-editor (master)
$ git branch
* master

Almir@PC-Miro MINGW64 /d/git/json-editor (master)
$ git branch develop/2.x

Almir@PC-Miro MINGW64 /d/git/json-editor (master)
$ git branch
  develop/2.x
* master

Almir@PC-Miro MINGW64 /d/git/json-editor (master)
$ git checkout develop/2.x
Switched to branch 'develop/2.x'

Almir@PC-Miro MINGW64 /d/git/json-editor (develop/2.x)
$ git checkout -B tailwind2.x
Switched to a new branch 'tailwind2.x'

Almir@PC-Miro MINGW64 /d/git/json-editor (tailwind2.x)
$ git branch
  develop/2.x
  master
* tailwind2.x

Almir@PC-Miro MINGW64 /d/git/json-editor (tailwind2.x)
$ cd src/themes/

Almir@PC-Miro MINGW64 /d/git/json-editor/src/themes (tailwind2.x)
$ git add tailwind.js

Almir@PC-Miro MINGW64 /d/git/json-editor/src/themes (tailwind2.x)
$ git commit -m 'Update tailwind'
[tailwind2.x 2474bf9] Update tailwind
 1 file changed, 599 insertions(+), 375 deletions(-)
 rewrite src/themes/tailwind.js (98%)

Almir@PC-Miro MINGW64 /d/git/json-editor/src/themes (tailwind2.x)
$ git push
fatal: The current branch tailwind2.x has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin tailwind2.x


Almir@PC-Miro MINGW64 /d/git/json-editor/src/themes (tailwind2.x)
$ git push --set-upstream origin tailwind2.x
ERROR: Permission to json-editor/json-editor.git denied to mirannda.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


Em qua, 14 de ago de 2019 às 15:08, Peter Klein <notifications@github.com>
escreveu:

**Comment by schmunk42** [comment]
I have protected the `develop/2.x` branch, btw - same like master

**Comment by pmk65** [comment]
> 
> 
> I have protected the `develop/2.x` branch, btw - same like master

Ah. That explains why I'm getting this error when pushing.

> remote: Resolving deltas: 100% (31/31), completed with 10 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/develop/2.x.
remote: error: Required status check "continuous-integration/travis-ci" is expected. At least 1 approving review is required by reviewers with write access.
To https://github.com/json-editor/json-editor.git
 ! [remote rejected] develop/2.x -> develop/2.x (protected branch hook declined)
error: failed to push some refs to 'https://github.com/json-editor/json-editor.git'

**Comment by mirannda** [comment]
PS D:\git\json-editor> git commit -m "Update Tailwind"
[tailwind2.x d1f6209] Update Tailwind
 1 file changed, 599 insertions(+), 375 deletions(-)
 rewrite src/themes/tailwind.js (98%)
PS D:\git\json-editor> git push --set-upstream origin tailwind2.x
ERROR: Permission to json-editor/json-editor.git denied to mirannda.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Em qui, 15 de ago de 2019 às 07:56, Peter Klein <notifications@github.com>
escreveu:

**Comment by mirannda** [comment]
@pmk65 @schmunk42 Following is the update for evaluation and publication.

```
JSONEditor.defaults.themes.tailwind = JSONEditor.AbstractTheme.extend({
    // Config options that allows changing various aspects of the output
    options: {
      disable_theme_rules: false, // Disable creation of Inline Style Rules
      label_bold: false, // Element labels bold
      object_panel_default: true, //Indicates whether to use rules as default or alternate style
      object_indent: true, // Indent nested object elements
      object_border: false, // Add border around object elements
      table_border: false, // Add border to array "table" row and cells
      table_hdiv: false, // Add bottom-border to array "table" cells
      table_zebrastyle: false, // Add "zebra style" to array "table" rows
      input_size: "small", // Size of input and select elements. "small", "normal", "large"
      enable_compact: false
    },
    // Custom stylesheet rules. (Does not suppert comma separated selectors)
    //  Will create a stylesheet in document head with the id "theme-spectre" if not exists.
    rules: {
      ".slider": "-webkit-appearance: none;-moz-appearance: none;appearance: none;background: transparent;display: block;border: none;height: 1.2rem;width: 100%;",
      ".slider:focus": "box-shadow: 0 0 0 0 rgba(87, 85, 217, .2); outline: none;",
      ".slider.tooltip:not([data-tooltip])::after": "content: attr(value);",
      ".slider::-webkit-slider-thumb": "-webkit-appearance: none;background: #F17405;border-radius: 100%;height: .6rem;margin-top: -.25rem;transition: transform .2s;width: .6rem;",
      ".slider:active::-webkit-slider-thumb": "transform: scale(1.25); outline: none;",
      ".slider::-webkit-slider-runnable-track": "background: #B2B4B6;border-radius: .1rem;height: .1rem;width: 100%;",

      "a.tooltips": "position: relative;display: inline;",
      "a.tooltips span": "position: absolute; white-space: nowrap; width:auto;padding-left:1rem;padding-right:1rem;color: #FFFFFF;background: rgba(56, 56, 56, 0.85);height:1.5rem;line-height: 1.5rem;text-align: center;visibility: hidden;border-radius: 3px;",
      "a.tooltips span:after": "content: '';position: absolute;top: 50%;left: 100%;margin-top: -5px;width: 0; height: 0;border-left: 5px solid rgba(56, 56, 56, 0.85);border-top: 5px solid transparent;border-bottom: 5px solid transparent;",
      "a:hover.tooltips span": "visibility: visible;opacity: 0.9;font-size:0.8rem;right: 100%;top: 50%;margin-top: -12px;margin-right: 10px;z-index: 999;",

      ".json-editor-btntype-properties+div": "font-size: .8rem;font-weight: normal;", // Fix fontsize in Properties modal
      textarea: "width:100%;min-height: 2rem;resize:vertical", // Prevent textarea from being resized horizontally
      table: "width:100%;border-collapse: collapse;", // Remove gap between table element borders
      ".table td": "padding: .0rem .0rem;", // reduce table padding
      'div[data-schematype]:not([data-schematype="object"])': "transition:.5s",
      'div[data-schematype]:not([data-schematype="object"]):hover': "background-color: #E6F4FE",
      'div[data-schemaid="root"]': "position: relative;width:inherit;display:inherit;overflow-x: hidden;z-index:10",
      'select[multiple]':'height:auto;',
      'select[multiple].from-select':'height:auto;',
      ".je-table-zebra:nth-child(even)": "background-color: #f2f2f2;",
      ".je-table-border": "border: 0.5px solid black;",
      ".je-table-hdiv": "border-bottom: 1px solid black;",
      ".je-border": "border:.05rem solid #3182CE",
      ".je-panel": "width:inherit; padding:.2rem;margin:.2rem;background-color: rgba(218,222,228,.1)",
      ".je-panel-top": "width:100%; padding:.2rem;margin:.2rem;background-color: rgba(218,222,228,.1)",
      ".required:after": 'content: " *";color: red;font:inherit;font-weight: bold;',
      ".je-desc": "font-size: smaller;margin: .2rem 0;",
      ".container-xl.je-noindent": "padding-left:0;padding-right:0;",
      ".json-editor-btntype-add": "color: white; margin:.3rem; padding: 0.3rem .8rem; background-color: #4299E1; box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-webkit-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-moz-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);",
      ".json-editor-btntype-deletelast": "color: white;margin:.3rem; padding: 0.3rem .8rem; background-color: #E53E3E; box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-webkit-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-moz-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);",
      ".json-editor-btntype-deleteall": "color: white;margin:.3rem; padding: 0.3rem .8rem; background-color: #000000; box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-webkit-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-moz-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);",
      ".json-editor-btn-save": "float:right; color: white; margin: 0.3rem; padding: 0.3rem .8rem; background-color: #2B6CB0; box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-webkit-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-moz-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);",
      ".json-editor-btn-back": "color: white; margin:.3rem; padding: 0.3rem .8rem; background-color: #2B6CB0; box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-webkit-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);-moz-box-shadow: 3px 3px 5px 1px rgba(4,4,4,0.2);",
      ".json-editor-btntype-delete": "color: #E53E3E; background-color: rgba(218,222,228,.1);margin:.03rem; padding: 0.1rem;",
      ".json-editor-btntype-move": "color: #000000; background-color: rgba(218,222,228,.1);margin:.03rem; padding: 0.1rem;",
      ".json-editor-btn-collapse": "padding: 0em .8rem;font-size:1.3rem;color: #E53E3E;background-color: rgba(218,222,228,.1);"
    },

    getGridContainer: function() {
      var el = document.createElement("div");
      el.classList.add("flex", "flex-col", "w-full");
      if (!this.options.object_indent) el.classList.add("je-noindent");
      return el;
    },
    getGridRow: function() {
      var el = document.createElement("div");
      el.classList.add("flex", "flex-wrap", "w-full");
      return el;
    },
    getGridColumn: function() {
      var el = document.createElement("div");
      el.classList.add("flex", "flex-col");
      return el;
    },
    setGridColumnSize: function(el, size, offset) {
      if (size > 0 && size < 12)
        el.classList.add("w-" + size + "/12", "px-1");
      else el.classList.add("w-full", "px-1");

      if (offset) el.style.marginLeft = (100 / 12) * offset + "%";
    },
    getIndentedPanel: function() {
      var el = document.createElement("div");
      if (this.options.object_panel_default)
        el.classList.add("w-full", "p-1");
      else
        el.classList.add("relative","flex","flex-col","rounded","break-words","border","bg-white","border-0","border-blue-400","p-1","shadow-md");
      if (this.options.object_border) el.classList.add("je-border");
      return el;
    },
    // Used for "type: array" with "format: tabs-top"
    getTopIndentedPanel: function() {
      var el = document.createElement("div");
      if (this.options.object_panel_default)
        el.classList.add("w-full", "m-2");
      else
        el.classList.add( "relative", "flex", "flex-col", "rounded", "break-words", "border", "bg-white", "border-0", "border-blue-400", "p-1", "shadow-md");
      if (this.options.object_border) el.classList.add("je-border");
      return el;
    },
    getTitle: function() {
      return this.schema.title;
    },
    getSelectInput: function(options, multiple) {
      var el = this._super(options);
      if (multiple) el.classList.add( "form-multiselect","block","py-0","h-auto","w-full","px-1","text-sm","text-black","leading-normal","bg-white","border","border-grey","rounded");
      else el.classList.add( "form-select","block","py-0","h-6","w-full","px-1","text-sm","text-black","leading-normal","bg-white","border","border-grey","rounded");
      if (this.options.enable_compact) el.classList.add("compact");
      return el;
    },
    afterInputReady: function(input) {
      if (input.controlgroup) return;
      input.controlgroup = this.closest(input, ".form-group");
      if (this.closest(input, ".compact")) {
        input.controlgroup.style.marginBottom = 0;
      }
    },
    getTextareaInput: function() {
      var el = this._super();
      el.classList.add("block","w-full","px-1","text-sm","leading-normal","bg-white","text-black","border","border-grey","rounded");
      if (this.options.enable_compact) el.classList.add("compact");
      el.style.height = 0;
      return el;
    },
    // Create input field for type="range"
    getRangeInput: function(min, max, step) {
      var el = this.getFormInputField("range");
      el.classList.add("slider");
      if (this.options.enable_compact) el.classList.add("compact");
      el.setAttribute("oninput", 'this.setAttribute("value", this.value)');
      el.setAttribute("min", min);
      el.setAttribute("max", max);
      el.setAttribute("step", step);
      return el;
    },
    getRangeControl: function(input, output) {
      var el = this._super(input, output);
      el.classList.add("text-center", "text-black");
      return el;
    },
    // Checkbox elements
    getCheckbox: function() {
      var el = this.getFormInputField("checkbox");
      el.classList.add("form-checkbox", "text-red-600");
      return el;
    },
    getCheckboxLabel: function(text, req) {
      var el = this._super(text, req);
      el.classList.add("inline-flex", "items-center");
      return el;
    },
    getFormCheckboxControl: function(label, input, compact) {
      label.insertBefore(input, label.firstChild); // Move input into label element
      if (compact) label.classList.add("inline-flex flex-row");
      return label;
    },
    getMultiCheckboxHolder: function(controls, label, description, infoText) {
      var el = this._super(controls, label, description, infoText);
      el.classList.add("inline-flex", "flex-col");
      return el;
    },
    // Radio elements
    getFormRadio: function(attributes) {
      var el = this.getFormInputField("radio");
      el.classList.add("form-radio", "text-red-600");
      for (var key in attributes) {
        el.setAttribute(key, attributes[key]);
      }
      return el;
    },
    getFormRadioLabel: function(text, req) {
      var el = this._super(text, req);
      el.classList.add("inline-flex", "items-center", "mr-2");
      return el;
    },
    getFormRadioControl: function(label, input, compact) {
      label.insertBefore(input, label.firstChild); // Move input into label element
      if (compact) label.classList.add("form-radio");
      return label;
    },
    getRadioHolder: function(schema, controls, label, description, infoText) {
      var el = this._super(controls, label, description, infoText);
      if (schema.options.layout == "h") el.classList.add("inline-flex", "flex-row");
      else el.classList.add("inline-flex", "flex-col");
      return el;
    },
    getFormInputLabel: function(text, req) {
      var el = this._super(text, req);
      if (this.options.label_bold) el.classList.add("font-bold");
      else el.classList.add("required");
      return el;
    },
    getFormInputField: function(type) {
      var el = this._super(type);
      if (["checkbox", "radio"].indexOf(type) < 0) el.classList.add("block","w-full","px-1","text-black","text-sm","leading-normal","bg-white","border","border-grey","rounded");
      if (this.options.enable_compact) el.classList.add("compact");
      return el;
    },
    getFormInputDescription: function(text) {
      var el = document.createElement("p");
      el.classList.add("block", "mt-1", "text-xs");
      if (window.DOMPurify) el.innerHTML = window.DOMPurify.sanitize(text);
      else el.textContent = this.cleanText(text);
      return el;
    },
    getFormControl: function(label, input, description, infoText) {
      var group = document.createElement("div");
      group.classList.add("form-group", "mb-1", "w-full");
      if (label) {
        label.classList.add("text-xs");

        if (input.type == "checkbox") {
          input.classList.add("form-checkbox","text-xs","text-red-600","mr-1");
          label.classList.add("items-center", "flex");
          label = this.getFormCheckboxControl(label, input, false, infoText);
        }

        if (input.type == "radio") {
           input.classList.add("form-radio", "text-red-600", "mr-1");
           label.classList.add("items-center", "flex");
           label = this.getFormRadioControl(label, input, false, infoText);
        }
        group.appendChild(label);

        if (["checkbox", "radio"].indexOf(input.type) < 0 && infoText) group.appendChild(infoText);
      }
      if (["checkbox", "radio"].indexOf(input.type) < 0) {
        if (this.options.input_size === "small") input.classList.add("text-xs");
        else if (this.options.input_size === "normal") input.classList.add("text-base");
        else if (this.options.input_size === "large") input.classList.add("text-xl");
        group.appendChild(input);
      }

      if (description) group.appendChild(description);

      return group;
    },
    getHeaderButtonHolder: function() {
      var el = this.getButtonHolder();
      el.classList.add("text-sm");
      return el;
    },
    getButtonHolder: function() {
      var el = document.createElement("div");
      el.classList.add("flex", "relative", "inline-flex", "align-middle");
      return el;
    },
    getButton: function(text, icon, title) {
      var el = this._super(text, icon, title);
      el.classList.add("inline-block","align-middle","text-center","text-sm","bg-blue-700","text-white","py-1","pr-1","m-2","shadow","select-none","whitespace-no-wrap","rounded");
      return el;
    },
    // Button for displaying infotext tooltip
    getInfoButton: function(text) {
      var tooltip = document.createElement("a");
      tooltip.classList.add("tooltips", "float-right");
      tooltip.innerHTML = "ⓘ";
      var span = document.createElement("span");
      span.innerHTML = text;
      tooltip.appendChild(span);

      return tooltip;
    },
    getTable: function() {
      var el = this._super();
      if (this.options.table_border) el.classList.add("je-table-border");
      else el.classList.add("table", "border", "p-0");
      return el;
    },
    getTableRow: function() {
      var el = this._super();
      if (this.options.table_border) el.classList.add("je-table-border");
      if (this.options.table_zebrastyle) el.classList.add("je-table-zebra");
      return el;
    },
    getTableHeaderCell: function(text) {
      var el = this._super(text);
      if (this.options.table_border) el.classList.add("je-table-border");
      else if (this.options.table_hdiv) el.classList.add("je-table-hdiv");
      else el.classList.add("text-xs", "border", "p-0", "m-0");
      return el;
    },
    getTableCell: function() {
      var el = this._super();
      if (this.options.table_border) el.classList.add("je-table-border");
      else if (this.options.table_hdiv) el.classList.add("je-table-hdiv");
      else el.classList.add("border-0", "p-0", "m-0");
      return el;
    },
    addInputError: function(input, text) {
      if (!input.controlgroup) return;
      input.controlgroup.classList.add("has-error");
      input.classList.add("bg-red-600");
      if (!input.errmsg) {
        input.errmsg = document.createElement("p");
        input.errmsg.classList.add("block", "mt-1", "text-xs", "text-red");
        input.controlgroup.appendChild(input.errmsg);
      } else {
        input.errmsg.style.display = "";
      }
      input.errmsg.textContent = text;
    },
    removeInputError: function(input) {
      if (!input.errmsg) return;
      input.errmsg.style.display = "none";
      input.classList.remove("bg-red-600");
      input.controlgroup.classList.remove("has-error");
    },
    getTabHolder: function(propertyName) {
      var el = document.createElement("div");
      var pName = typeof propertyName === "undefined" ? "" : propertyName;
      el.innerHTML ="<div class='w-2/12' id='" +pName +"'><ul class='list-reset pl-0 mb-0'></ul></div><div class='w-10/12' id='" +pName +"'></div>";
      el.classList.add("flex");
      return el;
    },
    addTab: function(holder, tab) {
      holder.children[0].children[0].appendChild(tab);
    },
    getTopTabHolder: function(propertyName) {
      var pName = typeof propertyName === "undefined" ? "" : propertyName;
      var el = document.createElement("div");
      el.innerHTML ="<ul class='nav-tabs flex list-reset pl-0 mb-0 border-b border-grey-light' id='" +pName +"'></ul><div class='p-6 block' id='" +pName +"'></div>";
      return el;
    },
    getTab: function(text, tabId) {
      var liel = document.createElement("li");
      liel.classList.add("nav-item","flex-col","text-center","text-white","bg-blue-500","shadow-md","border","p-2","mb-2","mr-2","hover:bg-blue-400","rounded");
      var ael = document.createElement("a");
      ael.classList.add("nav-link", "text-center");
      ael.setAttribute("href", "#" + tabId);
      ael.setAttribute("data-toggle", "tab");
      ael.appendChild(text);
      liel.appendChild(ael);
      return liel;
    },
    getTopTab: function(text, tabId) {
      var el = document.createElement("li");
      el.classList.add("nav-item","flex","border-l","border-t","border-r");
      var a = document.createElement("a");
      a.classList.add("nav-link","-mb-px","flex-row","text-center","bg-white","p-2","hover:bg-blue-400","rounded-t");
      a.setAttribute("href", "#" + tabId);
      a.setAttribute("data-toggle", "tab");
      a.appendChild(text);
      el.appendChild(a);
      return el;
    },
    getTabContent: function() {
      var el = document.createElement("div");
      el.setAttribute("role", "tabpanel");
      return el;
    },
    getTopTabContent: function() {
      var el = document.createElement("div");
      el.setAttribute("role", "tabpanel");
      return el;
    },
    markTabActive: function(row) {
      row.tab.firstChild.classList.add("block");
      if (row.tab.firstChild.classList.contains("border-b") == true) {
        row.tab.firstChild.classList.add("border-b-0");
        row.tab.firstChild.classList.remove("border-b");
      } else {
        row.tab.firstChild.classList.add("border-b-0");
      }
      if (row.container.classList.contains("hidden") == true) {
        row.container.classList.remove("hidden");
        row.container.classList.add("block");
      } else {
        row.container.classList.add("block");
      }
    },
    markTabInactive: function(row) {
      if (row.tab.firstChild.classList.contains("border-b-0") == true) {
        row.tab.firstChild.classList.add("border-b");
        row.tab.firstChild.classList.remove("border-b-0");
      } else {
        row.tab.firstChild.classList.add("border-b");
      }
      if (row.container.classList.contains("block") == true) {
        row.container.classList.remove("block");
        row.container.classList.add("hidden");
      }
    },
    getProgressBar: function() {
      var min = 0,
        max = 100,
        start = 0;

      var container = document.createElement("div");
      container.classList.add("progress");

      var bar = document.createElement("div");
      bar.classList.add("bg-blue","leading-none","py-1","text-xs","text-center","text-white");
      bar.setAttribute("role", "progressbar");
      bar.setAttribute("aria-valuenow", start);
      bar.setAttribute("aria-valuemin", min);
      bar.setAttribute("aria-valuenax", max);
      bar.innerHTML = start + "%";
      container.appendChild(bar);

      return container;
    },
    updateProgressBar: function(progressBar, progress) {
      if (!progressBar) return;

      var bar = progressBar.firstChild;
      var percentage = progress + "%";
      bar.setAttribute("aria-valuenow", progress);
      bar.style.width = percentage;
      bar.innerHTML = percentage;
    },
    updateProgressBarUnknown: function(progressBar) {
      if (!progressBar) return;

      var bar = progressBar.firstChild;
      progressBar.classList.add("progress","bg-blue","leading-none","py-1","text-xs","text-center","text-white","block");
      bar.removeAttribute("aria-valuenow");
      bar.classList.add("w-full");
      bar.innerHTML = "";
    },
    getInputGroup: function(input, buttons) {
      if (!input) return;

      var inputGroupContainer = document.createElement("div");
      inputGroupContainer.classList.add("relative","items-stretch","w-full");
      inputGroupContainer.appendChild(input);

      var inputGroup = document.createElement("div");
      inputGroup.classList.add("-mr-1");
      inputGroupContainer.appendChild(inputGroup);

      for (var i = 0; i < buttons.length; i++) {
        inputGroup.appendChild(buttons[i]);
      }

      return inputGroupContainer;
    }
  });



```

**Comment by pmk65** [comment]
@mirannda I had to re-import my develop/2.x branch and noticed I forgot to add 'fetch' to the list I described. So here's the complete list:
 
1) Take a copy of your Tailwind files and save them in another folder.
2) `git branch -D develop/2.x` (Delete the entire develop/2.x branch from your computer.)

3) `git clone https://github.com/json-editor/json-editor.git`  (Clones the repo)
4) `git fetch` (This will fetch all existing branches from repo)
5) `git branch develop/2.x` (This should put you into the develop/2.x branch. Use git branch to check if you are on the correct branch)

Now you have an up-to-date version of develop/2.x. Don't make changes here, but checkout a new local branch (6) and make your changes there.

6) `git checkout -B tailwind2.x` (this will create a new local branch develop/2.x, and put you on the branch)
7) `git pull` (This will pull down any new changes not on your local branch - ALWAYS DO THIS FIRST)

8) Move your Tailwind files back into the new tailwind2.x branch
9) Do a `git status` (There should only your Tailwind files in the list of changed filed)
10) Add and commit the Tailwind files, and then push.
11) Follow the instructions on how to push it to the repo.

**Pull request closed without merging**
