### PR TITLE
Fix of #629 

### PR DESCRIPTION
**Pull request by pmk65**
Fix of #629 - BS4 theme bug where basic tab was placed outside tabs container.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #629 
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ✔️

### CODE REVIEW

**Comment by schmunk42** [comment]
Tests fail, but it does not look related?!

**Comment by pmk65** [comment]
> 
> 
> Tests fail, but it does not look related?!

1st time the test failed on the "Unit" because I had a trailing space. 
But the current errors look weird. as the PR shouldn't affect the tests that fail.
Can you retrigger the test? (I remember there was a dropdown option where you could trigger the test, but I can no longer find/see it)

**Comment by schmunk42** [comment]
I splitted some of the opt-in tests to see which part triggers the problem https://github.com/json-editor/json-editor/tree/feature/hardening-tests-191211

Locally it works, so it might be some weird timing issue.

@pmk65 Does it also work with puppeteer? Also this commit https://github.com/json-editor/json-editor/pull/623 passed in PR state but fails now on master.

**Comment by pmk65** [comment]
Puppeteer shows 2 test errors.
image

**Comment by pmk65** [comment]
@schmunk42 I have fixed the problems with the `opt in optional properties` test.
The problem in `should trigger array (table) editing triggers` is Puppeteer specific (Works in Selenium/Webkit) and requires some changes in the html test page and test script in order to work using both systems.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
