### PR TITLE
support drag and drop for array item

### PR DESCRIPTION
**Pull request by skyshore2001**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Is backward-compatible?    | ✔️
| Tests pass?   | N.A.
| Fixed issues  | #448  
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ✔️

table1
table-2

### CODE REVIEW

**Comment by schmunk42** [comment]
@skyshore2001 Could you update your branch, we've fixed some build issues on `master`.

**Comment by skyshore2001** [comment]
I've rebased the branch on the lasted master.

**Comment by schmunk42** [comment]
@germanbisurgi Do we need an editor option for that, something like: `enable_drag_and_drop`?

**Comment by KemalSoysal** [comment]
> An enable_drag_and_drop option is strongly recommended. Default `false`

Should the option name be more specific for arrays?

**Comment by germanbisurgi** [comment]
I think is a good idea, like `enable_array_drag_and_drop`

**Comment by skyshore2001** [comment]
I consider the feature is safe, and it's not an experimental one. It does not conflict with others. So I don't think we need a new option. Just like in a file explorer, dragging is enabled by default.

**Comment by skyshore2001** [comment]
BTW, the feature does not add any visible component on UI.

**Comment by schmunk42** [comment]
> I consider the feature is safe, and it's not an experimental one. It does not conflict with others. So I don't think we need a new option. Just like in a file explorer, dragging is enabled by default.

Did you try this on a mobile device? It could be problematic if you have a list spanning the whole height.

I think an option like @germanbisurgi mentioned should be added.

**Comment by skyshore2001** [comment]
Dragging is not designed for mobile. I just tested 4 array formats on mobile. UI rendering is right, and dragging does not work as expected, because the mouse or drag events or Ctrl key for the action are all not supported on mobile device.
I don't understand the problematic scenario you mentioned. The implementation adds some event handlers (ignored on mobile)  to DOM and does not change any property or style, which seems not affect.

> > I consider the feature is safe, and it's not an experimental one. It does not conflict with others. So I don't think we need a new option. Just like in a file explorer, dragging is enabled by default.
> 
> Did you try this on a mobile device? It could be problematic if you have a list spanning the whole height.
> 
> I think an option like @germanbisurgi mentioned should be added.

**Review by germanbisurgi — APPROVED** [review]
I think this can be merged

**Pull request merged**
