### PR TITLE
fix: #812 (Deletion of array item corrupts form data )

### PR DESCRIPTION
**Pull request by germanbisurgi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #812
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by schmunk42** [comment]
@germanbisurgi Did  you verify this with the test mentioned in https://github.com/json-editor/json-editor/issues/812#issuecomment-817289054

**Comment by germanbisurgi** [comment]
No, i reproduce the bug and tested manually, can we merge his test or should i add them to my  branch?

**Comment by schmunk42** [comment]
> Can we merge his test...

@JElchison ?

**Comment by JElchison** [comment]
I'll be happy to validate this fix, and then submit a PR for my test separately. It will be completed within the next 24 hours. Thanks!

**Comment by JElchison** [comment]
Looks like @germanbisurgi already merged my test for me (while I was focused on my day job today).  Thanks!

**Comment by schmunk42** [comment]
Yeah, "happy accident" from our side :)

**Pull request merged**
