### PR TITLE
Interactive page disaster fix and #658

### PR DESCRIPTION
**Pull request by germanbisurgi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️?
| Fixed issues  | fixed interactive page disaster. Exposed abstract icon lib
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   |❌

### CODE REVIEW

**Comment by kameelyan** [comment]
Do we know when this will be released? What is your typical release schedule/workflow?

**Comment by schmunk42** [comment]
This is online, you might need to clear your browser caches.

**Comment by kameelyan** [comment]
I meant to NPM: I'm still seeing version 2.0.0.
image

**Comment by schmunk42** [comment]
I meant here: https://json-editor.github.io/json-editor/

**Comment by kameelyan** [comment]
Do we know when this change will be released into the npm package?

**Pull request merged**
