### PR TITLE
Dependency on field where multiple values were not possible possible

### PR DESCRIPTION
**Pull request by faustmann**
If no value of the choices matches with the current value then the variable dependenciesFulfilled is set to false

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   |  tested manually
| Fixed issues  | #862
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

Sorry, I have no Chrome-like browser installed. So I was not able to run the tests.

### CODE REVIEW

**Comment by schmunk42** [comment]
Does this really breaks BC?

**Comment by faustmann** [comment]
My fault, no. I adapted it.

**Comment by schmunk42** [comment]
Could we integrate a test on this page? `tests/pages/object-with-dependencies.html`

CC: @germanbisurgi

**Comment by joaopslins** [comment]
Hi folks, got into this issue while having a bug where dependencies as array wasn't working, and have found this PR that solves the issue. If there's something I can do to contribute to this PR let me know.

Also, I've noticed the other options usually check for `this.dependenciesFulfilled &&` (see image below), maybe this check is missing from the Array's case, which is what this PR is changing.

image

**Comment by aerogt3** [comment]
@faustmann thanks a lot for your fix! The dependency failure was causing huge issues for me, but not anymore :-)

**Review by abhishek-ejam — APPROVED** [review]

**Review by meekmeek35 — APPROVED** [review]

**Comment by meekmeek35** [comment]
When do you think this can be merged ? Many thanks

**Comment by schmunk42** [comment]
@germanbisurgi Please take a look

**Comment by martinsnajdr** [comment]
Please, this PR should be merged, it is just a minor bugfix, but this issue is causing (me) a big problem. 

Thanks!

**Review by schmunk42 — APPROVED** [review]

**Comment by schmunk42** [comment]
Builds are not starting :(

**Comment by germanbisurgi** [comment]
resolved in #971

**Comment by martinsnajdr** [comment]
Many thanks! That was really quick response 👍

**Pull request closed without merging**
