### PR TITLE
removed hardcoded styling from 'oneOf' switcher

### PR DESCRIPTION
**Pull request by coderofsalvation**
Removed hardcoded styling for the 'oneOf'-property (which i love to create conditional dynamic forms).
Not sure if this is the right timing, because it might effect the other styles.
On the other hand, it seems that not many people use 'oneOf' because i noticed a mixture of cleaned-up vs hardcoded ui-elements.

### CODE REVIEW

**Comment by schmunk42** [comment]
Could you check the tests, they're failing https://travis-ci.org/json-editor/json-editor/builds/520626824#L477-L481

**Comment by coderofsalvation** [comment]
oh wow didn't knew there was CI tied to this repo. Anyways, I added the missing semicolons. Let see what happens with the CI.

**Comment by pmk65** [comment]
@coderofsalvation You should also create a default stylesheet with the inline styles you are removing. Otherwise that information is lost after applying your patch.

**Comment by coderofsalvation** [comment]
Thank you for the review. I don't know what you mean with 'create a default stylesheet' (what file? where?).

**Comment by pmk65** [comment]
> 
> 
> Thank you for the review. I don't know what you mean with 'create a default stylesheet' (what file? where?).

@coderofsalvation Create a CSS file (name is not important) in the folder s`rc/styles/`. Then create `switcher` class selctor with the styles you have removed.

**Comment by coderofsalvation** [comment]
Hm this all is nice, but not straightforward, and probably triggers multiple iterations/linting issues.
Given the fact that we both are busy people, and not many people use oneOf, I'll close this pullrequest.
If people want to clear css properties, they can monkeypatch any theme using javascript because this library was written well.

**Pull request closed without merging**
