### PR TITLE
max and min for time, date and datetime local + tests

### PR DESCRIPTION
**Pull request by germanbisurgi**
| Q             | A
| ------------- | ---
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️

### CODE REVIEW

**Comment by schmunk42** [comment]
Tests are failing

```
  1) datetime
       should have correct initial value @datetime:
     Expected values to be strictly equal:
+ actual - expected
+ [
+   '{"time":"12:00","date":"2020-09-18","datetime-local":"2020-09-18T00:00"}'
+ ]
- '{"time":"12:00","date":"2020-09-18","datetime-local":"2020-09-18T00:00"}
```

**Comment by germanbisurgi** [comment]
can´t understand why test are passing with BUILD_ENV=build.prod but fail when BUILD_ENV=build.nonmin.travis

**Comment by schmunk42** [comment]
all versions have to pass, there should be no need for optional tests

**Review by schmunk42 — APPROVED** [review]

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
