### PR TITLE
Fix defaults

### PR DESCRIPTION
**Pull request by sirockin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️ and ❌ 
| Fixed issues  | #494
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   |❌

Although this fixes the original issue, for some reason I can't get the second codecept test to pass. When I run the steps from the test manually, everything works as expected. 

Can anyone advise I can easily debug codecept tests (ideally outside docker) or give any other advice on why this test may be failing?

### CODE REVIEW

**Comment by pmk65** [comment]
Try adding `I.click('[data-schemapath="root.button1"] button');` just after your comments. This will click the 1st button and force the "onchange" event to be triggered before getting the attribute from the 2nd button.

Maybe just switching the click and attribute checks around would work.

**Comment by sirockin** [comment]
> Try adding I.click('[data-schemapath="root.button1"] button'); just after your comments

Thanks for the feedback @pmk65 but unfortunately that didn't work. In any case I'd like to get to the bottom of why the test works on master but not on the new branch. I think I really need to debug the codecept test run. When I get a moment I'll try to work out how to do that.

**Comment by sirockin** [comment]
It looks like the cleave stuff was merged in late - looks like it's the `self` that's causing it.

I assumed (perhaps naively) that the e2e tests were comprehensive so would catch any bugs I introduced. 

 I'll change to this - please could you manually test for you your use case then add an e2e test for it?

**Comment by pmk65** [comment]
> Can anyone advise I can easily debug codecept tests (ideally outside docker) 

https://codecept.io/puppeteer

**Comment by pmk65** [comment]
> 
> 
> > Can anyone advise I can easily debug codecept tests (ideally outside docker)
> 
> https://codecept.io/puppeteer

Puppeteer is quite fast, and does not require Docker so It's a good alternative. Maybe we can have a setup for both?

>  should work with cleave.js library
    I am on page "string-cleave.html"
    I see element "[name="root[cleave_test]"]"
    I fill field "[name="root[cleave_test]"]", "12345678901234567890"
    I click ".get-value"
    I grab value from ".debug"
  √ OK in 1413ms

**Pull request merged**
