### PR TITLE
Removed 'rating' editor

### PR DESCRIPTION
**Pull request by pmk65**
Removed "rating" editor and updated "starrating" editor to accept/emulate "rating" editor options. See #389

Test case: https://is.gd/MHoA7a
Before patch: The "safety" property is generated using the "rating" editor.
After patch: The "safety" property is generated using the "starrating" editor.

### CODE REVIEW

**Comment by germanbisurgi** [comment]
I think this bug is related to the test fail:

Bildschirmfoto 2019-06-19 um 16 21 47

Bildschirmfoto 2019-06-19 um 16 36 00

changing `i` to `j` solves the console error. ButI have doubts because the for loop is nested in another for loop that uses `i`.
@pmk65  Am i missing some important detail?

**Comment by pmk65** [comment]
@germanbisurgi You are correct. There was a variable mismatch in the for loop.
I have corrected it now.

**Comment by schmunk42** [comment]
One error was fixed, but there's another one...

**Comment by pmk65** [comment]
> 
> 
> One error was fixed, but there's another one...

I think it's the test that needs to be rewritten. The file `tests/editors/rating_test.js` test looks like this.
````
...
  assert.equal(await I.grabAttributeFrom('[id="root[rating]5"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[id="root[rating]4"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[id="root[rating]3"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[id="root[rating]2"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[id="root[rating]1"]', 'disabled'), 'true');
...
````
I'm not sure, but it looks like each radio button has to be disabled separately, where `starrrating` disables the container.

**Comment by schmunk42** [comment]
@pmk65 Could you merge `master` on this branch, @germanbisurgi added a wait for "READY" https://github.com/json-editor/json-editor/pull/393/files#diff-9943549b79f1fb451b733f623d82afdbR7 ... this might help with this issue.

**Comment by schmunk42** [comment]
On your branch in the `rating_test.js` the output looks different.

Latest master
Bildschirmfoto von 2019-06-21 17-31-17

Your branch (no stars visible, different IDs and names)
Bildschirmfoto von 2019-06-21 17-32-12

**Comment by pmk65** [comment]
> 
> 
> On your branch in the `rating_test.js` the output looks different.
> 
That is because the master is using the "rating" editor. In my branch I removed the "rating" editor and modified the "starrrating" editor. So that it could accept same options as the "rating" editor.
"rating" uses the `maximum` property, where the "starrrating" uses `enum` list. So you end up with different layout (but same functionality)
I think that's the reason why the test fails, as they where made for "rating" editor layout.

**Comment by pmk65** [comment]
@schmunk42 I'll  modify my code, so the IDs are identical to the old rating editor layout. 
This might be a good idea, since it's based on the full path, where mine is just based on the field name. (And that could lead to problems in array situations)

**Comment by pmk65** [comment]
I have changed the id to same format as in "rating", but test still fails.

**Comment by germanbisurgi** [comment]
Made a PR to fix this (#395)

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
