### PR TITLE
Spectre/2.x

### PR DESCRIPTION
**Pull request by pmk65**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by pmk65** [comment]
Example: https://is.gd/XlkkI8

**Comment by pmk65** [comment]
Test schema is taken from #160

**Comment by schmunk42** [comment]
I don't think we should just remove duplicated messages, rather, like mentioned in #160 they should be more descriptive and the part in question should be highlighted.

**Comment by pmk65** [comment]
> 
> 
> I don't think we should just remove duplicated messages, rather, like mentioned in #160 they should be more descriptive and the part in question should be highlighted.

It's not that easy. due to how that type of arrors are resolved/rendered.
In the above testcase bot errors have the path "root", so they will be displayed under the element with `data-schemapath="root"` 
`not`, `anyOf`, `oneOf`, `allOf ` doesn't have a parent element, so no direct 'data-schemapath' is available. Instead it crops off the `not`, `anyOf`, `oneOf`, `allOf ` part of the path, which is why duplicates can occur.

**Comment by pmk65** [comment]
Filtering out duplicates is the best solution at the moment, until someone rewrites `src/editors/multiple.js`

**Comment by schmunk42** [comment]
>  Instead it crops off the not, anyOf, oneOf, allOf part of the path, which is why duplicates can occur.

Can't we just keep this information?

**Comment by pmk65** [comment]
> 
> 
> > Instead it crops off the not, anyOf, oneOf, allOf part of the path, which is why duplicates can occur.
> 
> Can't we just keep this information?

No, then the errors will not be displayed at all. 
As the errors needs a matching control element, which  not, anyOf, oneOf, allOf don't have.

**Comment by schmunk42** [comment]
I meant "as text" in the error message.

**Comment by pmk65** [comment]
The error messages already contains info about that: "Value must **not** validate against the provided schema" 

````json
  {
    "path": "root",
    "property": "not",
    "message": "Value must not validate against the provided schema"
  }
````

````javascript
  /**
   * When a value does not validate a 'not' schema
   */
  error_not: "Value must not validate against the provided schema",
````

Same goes for anyOf and oneOf.

**Comment by schmunk42** [comment]
Ah :) Now I get it. We should put that "not" in quotes or changes the message to something more understandable.

I still find it more helpful to have two messages, since you have two errors. If you have just one message and "fix" one of your inputs the message for the other "not" will still pop-up and this looks more confusing to me.

**Comment by pmk65** [comment]
> 
> 
> Ah :) Now I get it. We should put that "not" in quotes or changes the message to something more understandable.

Yes. The error messages needs an overhaul. 
> 
> I still find it more helpful to have two messages, since you have two errors. If you have just one message and "fix" one of your inputs the message for the other "not" will still pop-up and this looks more confusing to me.

How about a compromise (As I prefer a single error message 😁 ) where the error object is extended with a new property "errorcount" ?
Then the various `showValidationErrors` could display additional information if the count is higher than 1. 

**Example error object with errorcount**
````json
[
  {
    "path": "root.ports",
    "property": "pattern",
    "message": "Value must match the pattern ^[ ]*[1-9][0-9]{0,4}([ ]*-[ ]*[1-9][0-9]{0,4})?([ ]*,[ ]*[1-9][0-9]{0,4}([ ]*-[ ]*[1-9][0-9]{0,4})?)*[ ]*$",
    "errorcount": 1
  },
  {
    "path": "root",
    "property": "not",
    "message": "Value must not validate against the provided schema",
    "errorcount": 2
  }
]
````

**Comment by schmunk42** [comment]
Could you add a (simplified) page in `tests/pages`, I tried to created one with the schema provided above, but it really can't wrap my head around it.

**Comment by pmk65** [comment]
> 
> 
> Could you add a (simplified) page in `tests/pages`, I tried to created one with the schema provided above, but it really can't wrap my head around it.

It's way too complex for me too. I just used it as it produced the double errors. 😄 
Don't even know if it's valid. (I'm not good at using `not`, `anyOf`, and `oneOf` conditions.)

**Comment by schmunk42** [comment]
> > Could you add a (simplified) page in `tests/pages`, I tried to created one with the schema provided above, but it really can't wrap my head around it.
> 
> It's way too complex for me too. I just used it as it produced the double errors. 
> Don't even know if it's valid. (I'm not good at using `not`, `anyOf`, and `oneOf` conditions.)

I'll try to take a deeper look, but I really don't just want to discard the duplicated messages, without knowing about the root-cause of this issue.
We'd have to remember to re-add this when the validation is fixed and it might have strange side effects.

**Comment by pmk65** [comment]
The last PR only have one line that removes duplicates and adds the counter. The code is in separate function, so it should be very easy to change if needed.

https://github.com/json-editor/json-editor/blob/009f8fe5aef2e90403b44730ba544107b1aa4b8d/src/validator.js#L670-L691

**Comment by schmunk42** [comment]
> Then In the editor showValidationErrors function, we could add something like:
> `if (error.errorcount && error.errorcount > 1) error.message += ' (' + error.errorcount + ' errors)'; `
> 
> This would produce an error message like this:
> **Value must not validate against the provided schema (2 errors)**

Yes, that would be nice.

**Comment by pmk65** [comment]
> 
> 
> > Then In the editor showValidationErrors function, we could add something like:
> > `if (error.errorcount && error.errorcount > 1) error.message += ' (' + error.errorcount + ' errors)'; `
> > This would produce an error message like this:
> > **Value must not validate against the provided schema (2 errors)**
> 
> Yes, that would be nice.

I have added this feature in last commit. If we later want to have the duplicates displayed, all we have to do is to remove/comment out the `errors = this._removeDuplicateErrors(errors);`  line, and all will be as before.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
