### PR TITLE
Release 2.0.0-alpha.0

### PR DESCRIPTION
**Pull request by marc7000**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks backward-compatibility?    | ✔️/❌
| Tests pass?   | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ✔️/❌
| Added CHANGELOG entry?   | ✔️/❌

### CODE REVIEW

**Comment by schmunk42** [comment]
I can't merge, because tests are not passing.

CC: @pmk65

**Comment by germanbisurgi** [comment]
i am working on it

**Comment by germanbisurgi** [comment]
test fixed in #567

**Comment by schmunk42** [comment]
Merged Release-PR. Thank you!

**Pull request merged**
