### PR TITLE
Fix categories format on bootstrap 3 (#101)

### PR DESCRIPTION
**Pull request by dy93**
I Fix the categories format on bootstrap 3

### CODE REVIEW

**Comment by dy93** [comment]
ping

**Comment by dy93** [comment]
@germanbisurgi  ping

**Comment by schmunk42** [comment]
@germanbisurgi Is this ready to merge?

**Comment by germanbisurgi** [comment]
It works :)

**Comment by schmunk42** [comment]
Thank you!

**Comment by dy93** [comment]
you're welcome 👍!

**Pull request merged**
