### PR TITLE
Heatdutton changes cleaned

### PR DESCRIPTION
**Pull request by murb**
A few months ago [@heatdutton created a pull request](https://github.com/json-editor/json-editor/pull/15), which hasn't been merged up until this day, because of a merge conflict. This resolves this conflict + while reviewing I reduced two if-trees a slightly. 

Not sure if I'm entirely ok with the change `markTabActive: function(tab)` -> `markTabActive: function(row)`, although on later inspection it made sense. 

On a general note: this project could use some cleanup, similarly for this pull request, but I think @heatdutton's changes are valuable enough to let it pass.

### CODE REVIEW

**Comment by murb** [comment]
Note that I found some things I was relying on in a project I'm working on to be no longer working; I'll fix this first.

**Comment by murb** [comment]
My own custom theme was breaking the code. Nevermind, this can be merged...

**Comment by schmunk42** [comment]
We'll check this ASAP, thank you for your efforts.

**Comment by schmunk42** [comment]
Merged in https://github.com/json-editor/json-editor/commit/6fc274970c7a67259e93258e67022fd0a3f14e45 - thank you!

**Pull request closed without merging**
