### PR TITLE
Tests for Button Editor

### PR DESCRIPTION
**Pull request by pmk65**
My 1st attempt of writing an ConceptJS test.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by sirockin** [comment]
Thanks for these @pm65. I guess the build is failing because the tests aren't marked 'optional'

Do you want to fix that and merge or would you prefer me to copy the files into my branch for#494?

**Comment by pmk65** [comment]
@sirockin You can throw them into your PR. Where do you mark the test as "optional" ?

**Comment by sirockin** [comment]
> @sirockin You can throw them into your PR. 

will do
> Where do you mark the test as "optional" ?

Insert `@optional` at the end of the Scenario text, as per this one from `core_test.js`:

```javascript
Scenario('should watch form for changes @optional', async (I) => {
  I.amOnPage('core.html');
  I.dontSeeElement('.form-changed');
  I.click('.set-value');
  I.seeElement('.form-changed');
});
```

**Comment by sirockin** [comment]
I've confirmed on my own machine that these tests pass on the master branch but fail on development/2.x

**Pull request merged**
