### PR TITLE
Schema loader: Load schemas in parallel

### PR DESCRIPTION
**Pull request by chhill-redhat**
**Problem**
Loading a schema with many externally-referenced schemas can take a long time, because the schema API xhr calls are fetched serially, instead of in parallel. See `_asyncloadExternalRefs()` in `src/schemaloader.js`. 

I _think_ this behavior was introduced in [this commit](https://github.com/json-editor/json-editor/pull/1082/commits/58715ddd0f94ccb33eaf1b71b3f70c03f4739f86) from PR #1082. 

**The fix**
This new PR allows requests to run in parallel. The two main changes are:
1. Do not `await` each xhr request. Instead, when it's finished, add its results to the shared schemas list.
2. Make the top-level schemas loader wait until all schemas have been fetched. This is ugly code, because it uses a poller. There must be a better way to accomplish this using Promises or callbacks, but I couldn't find any other solutions.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | This PR only
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by schmunk42** [comment]
@germanbisurgi Why are Tests failing on Firefox?

**Comment by mariohernandez** [comment]
Any updates as to why tests are failing in Firefox?  I'd love to have this merged.

**Comment by mariohernandez** [comment]
Hi @germanbisurgi is there anything we can do to help you get this MR through?

**Comment by schmunk42** [comment]
@mariohernandez Can you reproduce the failing FF tests locally?

**Comment by mariohernandez** [comment]
Hi @schmunk42 we actually are able to reproduce the failing FF tests locally.  We are looking into addressing this issue and we'll update the PR soon.  Thanks.

**Comment by chhill-redhat** [comment]
@schmunk42 , I am able to consistently reproduce the failing tests locally, both in Chrome and Firefox browsers. However, I am not able to figure out how to fix this. It's failing because there's not a DOM node with text "Error Messages". When I load that page up manually (http://localhost:8080/tests/pages/error-messages.html), the expected text appears correctly.

I'm new to CodeceptJS tests. Any tips to help debug this?
Running the tests works, but it takes a while on my local (`npm run docker-test`). Do you know if there's a way to run the tests faster? Maybe running the tests locally without Docker is faster? When I run `npm run cp:test`, I get error `Chromium revision is not downloaded. Run "npm install" or "yarn install"` (even though I've installed npm dependencies).

Thanks for any help!
cc: @germanbisurgi

**Comment by germanbisurgi** [comment]
Sounds like a timing problem. I can take a look at this.

**Comment by germanbisurgi** [comment]
Adding `I.waitForElement('.je-ready')` In `core_test.js` under `@errors-messages` fix the test failing.

Bildschirmfoto 2022-05-10 um 08 59 09

**Comment by germanbisurgi** [comment]
> Make the top-level schemas loader wait until all schemas have been fetched. This is ugly code, because it uses a poller. There must be a better way to accomplish this using Promises or callbacks, but I couldn't find any other solutions.

A better way to do this can be to use `Promise.all()`. 

> The Promise.all() method takes an iterable of promises as an input, and returns a single [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that resolves to an array of the results of the input promises. This returned promise will resolve when all of the input's promises have resolved, or if the input iterable contains no promises. It rejects immediately upon any of the input promises rejecting or non-promises throwing an error, and will reject with this first rejection message / error.

Hier is a nice [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) for that. It have good examples too.
Hier is a plan with pseudocode:

First the `asyncLoad()` method should be changed to return a new Promise.

Then every load promise should be stored in an array of promises.

```javascript
const promises = [
  this.load(params),
  this.load(params),
  this.load(params),
  ...
]
```

And then the Promise.all() takes the promise array and will resolve when all the promises resolve.

```javascript
Then call Promise.all(promises).then(() => {
  // do stuff here
})
```

**Comment by chhill-redhat** [comment]
Thank you for these suggestions, @germanbisurgi . 

I'm hoping to try these ideas soon. I gave up on Promises originally because we didn't know how many schema requests would be required (because of nested schema references). This idea might help with this: https://stackoverflow.com/a/37819138

**Comment by schmunk42** [comment]
It would be interesting to know how eg. 100 parallel requests are handled by the browser? 
AFAIR (years ago) it was limited to about 6 request in parallel.

**Comment by chhill-redhat** [comment]
@schmunk42 , I opened a separate PR to help with performance (https://github.com/json-editor/json-editor/pull/1162). Instead of loading the xhr requests in parallel, this new PR caches the fetched schemas in the browser. (This makes subsequent schema builds very fast.) Maybe we close this current PR in favor of the caching one?

**Comment by schmunk42** [comment]
Closing in favour of #1162

**Pull request closed without merging**
