### PR TITLE
fixes #536 - ipv4 format breaks editor when used in 'allOf' inheritan…

### LINKED ISSUE #536: ipv4 format breaks editor when used in 'allOf' inheritance hierarchy
### General information

When a schema uses `allOf` to inherit from a parent definition, and the parent contains a property with `type:"string"` and `format:"ipv4"`, the editor does not not display, and the browser console shows the following error:
```
Uncaught TypeError: Cannot read property 'ipAddress' of undefined
```

Commenting out the resolver assignment code for the ip editor (`defaults.js` lines 529-531) gets rid of the error (as well as the double error message from #534).

- json-editor version: develop/2.x

### Steps to reproduce the behavior

1. Create a new html page string-formats2.html in the tests folder (see below)
1. Run npm run debug
1. Navigate to http://localhost:8080/tests/pages/string-formats2.html

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>wysiwyg-sceditor</title>

  <!-- json editor -->
  <script src="../../dist/jsoneditor.js"></script>

  <!-- jquery -->
  <script src="./../../node_modules/jquery/dist/jquery.min.js"></script>

</head>
<body>

<textarea class="debug" cols="30" rows="10"></textarea>
<button class='get-value'>Get Value</button>
<div class='container'></div>

<script>
  var container = document.querySelector('.container');
  var debug = document.querySelector('.debug');
  var schema ={
    "definitions": {
        "parent": {
            "properties": {
                "ipAddress": {
                    "title": "IP Address",
                    "type": "string",
                    "format": "ipv4"
                }
            },
            "required": [
                "ipAddress"
            ]
        },
    },
    "type": "object",
    "allOf": [
        {
            "$ref": "#/definitions/parent"
        }
    ]
};
  
  var editor = new JSONEditor(container, {
    schema: schema
  });

  document.querySelector('.get-value').addEventListener('click', function () {
    debug.value = JSON.stringify(editor.getValue());
  });

</script>

</body>
</html>

```

### PR DESCRIPTION
**Pull request by pmk65**
…ce hierarchy

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #536
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by pmk65** [comment]
> 
> 
> Hi @pmk65 thanks for the updates. Just one question - does `this.pattern` ever change? If not could you declare it as a `const` rather than as a member of the class?

Both `this.pattern` and `this.patternmessage` changes based on the `format`. I made them part of class to avoid having to pass two additional parameters to the `setValidatorPatterns` function.

**Comment by sirockin** [comment]
Hi @pmk65, understood.

Generally it's considered best practice not to hold unnecessary mutable state in an object - it makes code more fragile,  less maintainable and readable. My immediate questions on seeing those variables were, 'how long do they get stored? who else may change them? etc'. 

What were your objections to passing them as parameters to the setValidatorPatterns()? I think that would be clearer and more maintainable.

Also any particular reason for using a chain of `if/else` statements instead of `switch` in prebuid()?

**Comment by pmk65** [comment]
@sirockin I think we should remove the `ip.js` editor then. There's no point in having an editor that just sets the Cleave.js options, which you can add to the schema yourself.

**Comment by sirockin** [comment]
Hmmm that's up to you but it's valuable nonetheless, no? 

Perhaps we should try to get some feedback from @schmunk42 ?

**Comment by pmk65** [comment]
> 
> Hmmm that's up to you but it's valuable nonetheless, no?

Yes, but you can set them options yourself in the schema. Also the ipv4 cleave settings expects the input to be in xxx.xxx.xxx.xxx format, so that would prevent entering the value in a different format which you have opened up for.

I just added support for [IMask](https://imask.js.org/guide.html), a library similar to Cleave (But only masks the input.). In some cases this might be a better solution than using Cleave.

**Comment by schmunk42** [comment]
I think it is OK to have a pre-defined format or shorthands for ipv4 and ipv6.

**Comment by sirockin** [comment]
@pmk65  Those IMask additions sound like a good idea - this is more your area than mine but I definitely like the way this code is moving

@schmunk42 sorry I'm not clear on what you're saying there.

**Comment by schmunk42** [comment]
I thought you asked me for my opinion about having `ip.js` - and my understanding is that it is relevant for having a shorthand for an IP editor instead of specifying the cleave options manually.

**Comment by sirockin** [comment]
> I thought you asked me for my opinion about having `ip.js` - and my understanding is that it is relevant for having a shorthand for an IP editor instead of specifying the cleave options manually.

Okay cool well it looks as if we're all on the same page then. Shall we merge or @pmk65 do you have anything to add?

**Comment by pmk65** [comment]
> 
> 
> I thought you asked me for my opinion about having `ip.js` - and my understanding is that it is relevant for having a shorthand for an IP editor instead of specifying the cleave options manually.

True, but it also makes it harder to change from the users point of view. As you can't see the config options applied to the field, without digging into the source.
Letting the user choose manually (and maybe use a different library other than Cleave), seems like a better option to me. Specially since the IP editor doesn't really do anything except for setting Cleave config.

**Comment by sirockin** [comment]
If all we were really seeking to achieve was validation, I'm not clear on what the point was of having an editor.

**Comment by sirockin** [comment]
But for what it's worth, I think having a default editor setup for these formats *is* really valuable. Even if they're not perfect now (eg not allowing shortened ipv6) they're something really handy to build on. And am I right in thinking that if a user doesn't want them she can override in the schema options?

**Comment by pmk65** [comment]
> 
> But for what it's worth, I think having a default editor setup for these formats _is_ really valuable. Even if they're not perfect now (eg not allowing shortened ipv6) they're something really handy to build on. And am I right in thinking that if a user doesn't want them she can override in the schema options?

Yes. but that would require some specific documentation on the IP editor with information on how to override it, and what the default options are. Otherwise it just ends up as one of the "undocumented features" (And we already got too many of those).

**Comment by sirockin** [comment]
Well we *could* document it :-)

**Pull request merged**
