### PR TITLE
Test case for Cleave.js

### PR DESCRIPTION
**Pull request by pmk65**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

String test for "cleave.js" library. 
Note: I still haven't gotten Docker to work, so test is _untested_ 😁

### CODE REVIEW

**Comment by sirockin** [comment]
Thanks @pmk65  I've pulled the relevant code into my `fix_defaults` branch and running tests now.

What's your issue with Docker? You're on Windows like me, right?

**Comment by pmk65** [comment]
Stupid Windows 10 OEM Home Edition. Won't let me install Docker as it requires the Pro version. 😞 
I tried the Docker Toolbox, but couldn't get that to work either.

**Comment by sirockin** [comment]
Damn! In any case it should be possible to run Codecept tests without Docker - it's important for debugging failing tests. I'll look more closely at it when I get time.

**Comment by sirockin** [comment]
@pmk65 I've moved the new code from this PR into #499. The test didn't pass on my machine so I've marked it '@optional' before pushing it. Looking now at how to run codecept without docker.` Can we resume this conversation on #499?

**Comment by pmk65** [comment]
Did you run `npm install` before running test?
As I have updated package.json (I put cleave.js as a "dependencies", but I think it should be a "devDependencies")

**Comment by sirockin** [comment]
Ah no, sorry. Yes you're right it's better in dev-dependencies. I'll add that now and resubmit.

**Comment by pmk65** [comment]
> 
> 
> Ah no, sorry. Yes you're right it's better in dev-dependencies. I'll add that now and resubmit.

I always forget to run `npm install` myself and my PR was a bit messy. 😁

**Comment by sirockin** [comment]
If you could just update in in #499 and remove '@optional' from the Scenario, that should rerun the (now working) test.

**Pull request closed without merging**
