### PR TITLE
Various minor fixes.

### PR DESCRIPTION
**Pull request by heathdutton**

### CODE REVIEW

**Comment by schmunk42** [comment]
Changes look good to me.

**Comment by schmunk42** [comment]
The changes of the last two commits are quite large, it would be better to create a separate PR for them.

**Comment by schmunk42** [comment]
This looks like a cool feature, but I think we should not add it to the initial 1.0.0 release.

@heathdutton Could you merge/rebase this with master so that there are no conflicts.

**Comment by heathdutton** [comment]
Will do.

**Comment by Mikescops** [comment]
Will this branch be merge soon ? I think improvements made here are quite important for the project.

**Comment by schmunk42** [comment]
There are some conflicts in `docs/index.html`, but they don't look problematic.

CC: @germanbisurgi @marc7000 Can you have a look at this.

**Comment by murb** [comment]
I have created two new pull requests that solves the conflict. I hope you appreciate offering a choice between two options. I won't feel hurt when you decide to merge #73 instead of #72 though.

**Comment by schmunk42** [comment]
Merged in https://github.com/json-editor/json-editor/commit/6fc274970c7a67259e93258e67022fd0a3f14e45 - thank you!

**Pull request closed without merging**
