### PR TITLE
988: Updates schemaloader JSON pointer functionality

### PR DESCRIPTION
**Pull request by cybtachyon**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #988 
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ✔️

### CODE REVIEW

**Comment by cybtachyon** [comment]
One failing Firefox test, and I'm not sure why since it succeeds in chrome.

Element appears to display on a manual test of advanced.js just fine.

**Review by schmunk42 — APPROVED** [review]
LGTM, CC: @germanbisurgi

**Comment by cybtachyon** [comment]
@germanbisurgi @schmunk42 What is left to do to get this merged? Anything I can help with?

**Comment by schmunk42** [comment]
@cybtachyon Test are running shaky, but I don't have much time to investigate atm.

**Pull request closed without merging**
