### PR TITLE
enumSource reorder fix, preserve value at Move Up or Down for 2.x

### PR DESCRIPTION
**Pull request by pmk65**
#187 ported to 2.x version. 
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ❌

@schmunk42 I noticed an odd behavior when using the provided example. When the new option `enum_source_value_auto_select` is NOT ENABLED (Default behavior) and you move an item from `possibleFonts` up/down, you get duplicate entries in `selectedFonts`

So should we enable the new option by default?

### CODE REVIEW

**Comment by schmunk42** [comment]
From my understanding and what has been written [here](https://github.com/json-editor/json-editor/pull/187#discussion_r225845442) we should enable it by default.

**Comment by schmunk42** [comment]
@pmk65 it would be great if we could merge this and close the other ;) Will you make the setting a default?

**Comment by pmk65** [comment]
Done. What description should we give to the option `enum_source_value_auto_select` ?
I'm not quite clear on that myself.

**Comment by schmunk42** [comment]
> Done. What description should we give to the option `enum_source_value_auto_select` in README.md ?
> I'm not quite clear on that myself. _Preserve value at Move Up or Down?_

Yeah, would be fine with me. CC: @germanbisurgi

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
