### PR TITLE
Fix of #618 - links are placed AFTER the description

### PR DESCRIPTION
**Pull request by pmk65**
Now places the link BEFORE description (if available) or at bottom of container.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ❌
| Fixed issues  | #618
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ✔️

### CODE REVIEW

**Comment by pmk65** [comment]
Not sure why, but the tests fail at:

e]   ✖ It should display button Labels: materialize | null in 1608ms
e]   ✖ It should display button Labels: foundation6 | null in 2630ms

@germanbisurgi

**Comment by pmk65** [comment]
Both the themes that fails in test are not updated to 2.x format which might be why they fail. 

Can we remove the 1.x themes from the tests? There's really no point in testing against those if they are not updated.

**Comment by schmunk42** [comment]
> @schmunk42 Both the themes that fails in test are not updated to 2.x format which might be why they fail.
> 
> Can we remove the 1.x themes from the tests? There's really no point in testing against those if they are not updated.

Yeah, makes no sense I think. Which ones do you want to keep?

**Comment by pmk65** [comment]
These are the themes currently in 2.x format:

    barebones
    html (the default)
    bootstrap4
    spectre
    tailwind

**Comment by schmunk42** [comment]
@pmk65 WIll you remove the tests for the unsupported themes?

**Comment by pmk65** [comment]
Will do. I just wasn't sure if it was something you or I should do 😕

**Comment by pmk65** [comment]
@schmunk42 Weird Travis errors again. Can you rerun the test?

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
