### PR TITLE
Webpack

### PR DESCRIPTION
**Pull request by sirockin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #447
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ❌ - but I've added release-notes.md to the root

### CODE REVIEW

**Comment by pmk65** [comment]
@sirockin There's a few simple merge conflicts that needs to be resolved before we can review it.

**Comment by sirockin** [comment]
Tried an online merge but that's failing tests. Will try fixing that now.

**Comment by sirockin** [comment]
You'll see that I added lines to `.travis.yml` so that it would run the unit tests. However, now that I've seen the build running, I see that it's not optimal since the same script runs twice, one for each environment.

**Comment by pmk65** [comment]
@sirockin I get this output after running "npm install"
````
> npm run build


> @json-editor/json-editor@1.4.0-beta.0 build C:\GITHub\json-editor
> rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail

<w> [webpack.Progress] 6987ms building
<i> [webpack.Progress] 36ms chunk assets processing
<w> [webpack.Progress] 2587ms chunk asset optimization
<i> [webpack.Progress] 444ms after chunk asset optimization
<i> [webpack.Progress] 69ms emitting
<i> [webpack.Progress] 20ms after emitting
Hash: aeca6d9804dfd13b127f
Version: webpack 4.39.1
Time: 10323ms
Built at: 2019-08-20 22:15:57
            Asset     Size  Chunks                    Chunk Names
    jsoneditor.js  257 KiB       0  [emitted]  [big]  jsoneditor
jsoneditor.js.map  723 KiB       0  [emitted]         jsoneditor
Entrypoint jsoneditor [big] = jsoneditor.js jsoneditor.js.map
 [0] ./src/utilities.js 2.07 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
 [1] ./src/editor.js 19.4 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
 [2] ./src/editors/string.js 10.2 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
 [5] ./src/editors/select.js 12.1 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
 [7] ./src/editors/multiselect.js 7.2 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
 [8] ./src/themes/foundation.js 15.9 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
 [9] ./src/core.js 27.7 KiB {0} [built]
     factory:172ms building:3096ms = 3268ms
[10] ./src/editors/array.js 27.8 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
[11] ./src/editors/number.js 1.23 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
[12] ./src/validator.js + 1 modules 24.1 KiB {0} [built]
     | ./src/validator.js 22.8 KiB [built]
     |     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
     | ./src/validators/ip-validator.js 1.24 KiB [built]
     |     [9] 3268ms -> [] 3027ms -> factory:2121ms building:842ms = 9258ms
[13] ./src/defaults.js 16.8 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
[16] ./src/ie9.js 1.72 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
[17] ./src/themes/html.js 2.97 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
[18] ./src/themes/bootstrap2.js 9.25 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
[19] ./src/themes/bootstrap3.js 8.9 KiB {0} [built]
     [9] 3268ms -> factory:3025ms building:2ms dependencies:1924ms = 8219ms
    + 66 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  jsoneditor.js (257 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  jsoneditor (257 KiB)
      jsoneditor.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
npm WARN eslint-plugin-import@2.9.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.npm WARN eslint-plugin-react@7.7.0 requires a peer of eslint@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 455 packages from 368 contributors, removed 408 packages, updated 37 packages and audited 9995 packages in 141.465s
found 0 vulnerabilities
````

**Comment by sirockin** [comment]
Thanks @pmk65, that all looks pretty normal.

The size warning is because we haven't yet broken down the build into more than one bundle - I mentioned that as a TODO in the release notes. Nonetheless, the bundle size is only just over the recommended size and is around the same size as that produced by the old Grunt build.

**Comment by pmk65** [comment]
I read in your readme that you have keept the IE9 polyfill. I think we should drop that (there's plenty other ways to do polyfills) and also the jQuery wrapper.

**Comment by sirockin** [comment]
@schmunk42  thanks for your positive feedback! 

@pmk65:
1. ie9, I agree but will need to look further at how to do this optimally
2. jquery wrapper, again I agree in principle but wanted to avoid breaking changes - perhaps we can just place it in as separate bundle?
3. themes - yes definitely agree they are ideal candidates for lazy load bundles.

Do you want me to try to fix all the above in this PR or shall we raise this as a new issue?

**Comment by pmk65** [comment]
> @pmk65:
> 
>     1. ie9, I agree but will need to look further at how to do this optimally
> 
>     2. jquery wrapper, again I agree in principle but wanted to avoid breaking changes - perhaps we can just place it in as separate bundle?

2.x will involve breaking changes. So removing the IE9 polyfill and jQuery wrapper is a minor thing. 
You can include external IE9 polyfill from external source if needed and create your own jQuery wrapper if you want. 

Another thing (you already did something similar with your IP validator implementation) we should do, is to move the resolver code from default.js, into separate files. That way it will be easier to exclude editors. (There's a [PR ](https://github.com/jdorn/json-editor/pull/322/commits/7e9dcbfa31bb13c9f499ad56c0fd57a56a486812) from the old jdorn repo that does that.)

> 
> Do you want me to try to fix all the above in this PR or shall we raise this as a new issue?

I'm good with this PR, so I think we should resolve the other issues in a new issue.

**Comment by pmk65** [comment]
Small thing. 
In the `dist` folder there's only 2 files: `jsoneditor.js` (which is minified) and `jsoneditor.js.map`
Would it be possible to create a set of unminified files and a set of minified with the **.min** extension as before?

**Comment by schmunk42** [comment]
Actually we do not have a `dist` folder at all atm. - and it should be kept like that, since you'd need to rebuild it for every change.

**Comment by sirockin** [comment]
@pmk65 

> In the dist folder there's only 2 files: jsoneditor.js (which is minified) and jsoneditor.js.map
Would it be possible to create a set of unminified files and a set of minified with the .min extension as before?

At first glance it doesn't seem easy to acheive but I can look into it. What's the use case for this? Do you want the unminimized files shipped with the distribution or just available for debugging? 

If the latter, it's very easy to debug the generated code via Chrome Tools since it recognises the source map and lets you set breakpoints etc in the original code.  To do so: 

1. Start test server/autocompilation using `npm start`. 
2. Navigate in Chrome to a test page (say [http://localhost:8080/tests/pages/array-selectize.html])
3. Open Chrome dev tools sources tab
4. Expand webpack:// node then open ./src/{your-source-file-name}

**Comment by sirockin** [comment]
@pmk65 
> Would it be a good idea to "split" the editors into mandatory (string, array, object etc.) and optional (SignaturePad, StarRting, Select2 etc.) ?
I can see you currently have them in alphabetic order.

It could be a good idea to split the non-mandatory editors into seperate bundles so that they load only when needed. Obviously when bundling there is always a trade-off between time gained on initial load vs number of round trips required to complete the load.

**Comment by schmunk42** [comment]
@pmk65 @sirockin I'd be fine with merging this. We can fine-tune the webpack config later.

**Comment by sirockin** [comment]
Any progress on merging this?

**Comment by schmunk42** [comment]
Done. Thank you! 

My above message was actually a question, sorry for forgetting the "?"

**Comment by sirockin** [comment]
Thanks Tobias! Yes I've started work on the optimisation on a separate branch. It's a little tricker than I thought though - lazy loading requires implementing es2016 language features (async etc) but it will be doable.

**Comment by pmk65** [comment]
> 
> > In the dist folder there's only 2 files: jsoneditor.js (which is minified) and jsoneditor.js.map
> > Would it be possible to create a set of unminified files and a set of minified with the .min extension as before?
> 
> At first glance it doesn't seem easy to acheive but I can look into it. What's the use case for this? Do you want the unminimized files shipped with the distribution or just available for debugging?

It's always good to have both a un-minified and a minified version in the distibrution. Specially on CDN.
In the playground I use the un-minified version, as it's "not" possible to override functions at run time. (It is possible, but the variables are minified, so the override code dosn't make sense when compared to the source)

**Comment by sirockin** [comment]
Hi @pmk65 I can certainly look into this. Now that this PR has been merged, do you think you could raise this as a separate issue so we can discuss there?

**Comment by pmk65** [comment]
@sirockin Shouldn't the version say 2.x and not 1.4 ?

> npm run build
> @json-editor/json-editor@1.4.0-beta.0 build C:\GITHub\json-editor
> rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail

**Comment by sirockin** [comment]
> @sirockin Shouldn't the version say 2.x and not 1.4

Ah maybe - I just copied the header from the version of intro.js that I forked from 2.x. Are you able to upate directly without me submitting a new PR? Otherwise I can update in my webpack_optimization PR.

**Comment by pmk65** [comment]
@sirockin Just do it in you next PR. No need for me to mess with the setup files when you are working on those. 😄

**Comment by sirockin** [comment]
I'll set version in package.json to 2.0.0 for now then.

**Comment by schmunk42** [comment]
> I'll set version in package.json to 2.0.0 for now then.

@sirockin `2.0.0-dev` please

**Pull request merged**
