### PR TITLE
Un-updated Themes and Iconlibs removed (commented out)

### PR DESCRIPTION
**Pull request by pmk65**
- Removed (commented out) Bootstrap 2/3, Foundation and Materialize Themes.
- Removed (commented out) Bootstrap 2/3, Foundation and Materialize Iconsets.

Files have **NOT** been removed from `src/`, so it's possible to include them again if needed.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #643 
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ✔️

**Size differences:**
unminified: 516kb vs **460kb**
    minified: 253kb vs **226kb**

Not sure if we should merge this yet. Was just created to see how much smaller the lib would be without them.

### CODE REVIEW

**Comment by pmk65** [comment]
Several of the tests needs an update because they use one of the removed themes. 
I'll continue the work on this PR until it passes tests.

**Comment by pmk65** [comment]
@schmunk42 @germanbisurgi All tests now pass using Puppeteer, but  these 2 fails the Travis tests,
✖ grid-strict rows and columns in 200ms
✖ grid rows and columns in 226ms

Can any of you take a look and see if you can fix it?

**Comment by schmunk42** [comment]
Please remove the files, we can get them from git if needed, a link or commit-SHA1 would be enough.

**Comment by pmk65** [comment]
> 
> 
> Please remove the files, we can get them from git if needed, a link or commit-SHA1 would be enough.

The reason I choose to keep the files, is that *maybe* someone using the un-updated themes might decide to update them. 😁 

Then when we release the non-beta version, they will be finally removed. (That's the info I have added in readme.md)

But there's still 2 tests that fails Travis test.

**Comment by pmk65** [comment]
@schmunk42 Tests passes now. So rerun the tests. (Travis failed on 1 test due to the usual weird error)

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
