### PR TITLE
Replace property name in the error_required message with human readable property title

### PR DESCRIPTION
**Pull request by Krivich**
As user I want to see human-readable error message if a requierd property is not populated. 
Act: error text with the property name as the reference to the failure field
Exp: error test with the property title if exists or otherwise property  name, as the reference to the failure field

This problem is very actual for multi-language projects because user might be not able to match English name of the property and form field label on his own language.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by Krivich** [comment]
Hi. Is there any update on this PR please?

**Review by schmunk42 — APPROVED** [review]
LGTM, since tests are passing.

@germanbisurgi WDYT?

**Comment by robocoder** [comment]
Would this be too fancy?
```
message: this.translate('error_required', [(((schema || {}).properties || {})[e] || {}).title || el])
```

**Comment by schmunk42** [comment]
> Would this be too fancy?
> 
> ```
> message: this.translate('error_required', [(((schema || {}).properties || {})[e] || {}).title || el])
> ```

a comment would be good ;)

**Comment by germanbisurgi** [comment]
The less fancier the better :)

**Review by germanbisurgi — APPROVED** [review]

**Comment by schmunk42** [comment]
@Krivich Is there a special reason, why this is in draft stage?

**Comment by Krivich** [comment]
@schmunk42, no. There was no review for a long time and github offered to convert PR to draft. I supposed this action can let my docker download patched library with npm install somehow, so I clicked the button. It was the wrong assumption. Sorry.

**Comment by Krivich** [comment]
Hi. What I can do to help make it availabe in release package?

**Comment by schmunk42** [comment]
> Hi. What I can do to help make it availabe in release package?

It's in "Draft Stage" so we can not merge it.
But I can convert it to "Ready for review", that's why I was asking :)

**Comment by Krivich** [comment]
Hi. What can I do to help to release this feature?

**Comment by schmunk42** [comment]
Could you update this PR with `master`, please.

I've switched to GitHub actions, since Travis failed too often due to missing credits. And now GH-actions must pass.

Sorry for the inconvenience.

**Comment by Krivich** [comment]
Rebased and pushed.

**Comment by schmunk42** [comment]
Thank you!

**Comment by Krivich** [comment]
Sorry, when I can expect my npm to install the updated version with this fix?

**Comment by schmunk42** [comment]
We're preparing it https://github.com/json-editor/json-editor/issues/969

**Pull request merged**
