### PR TITLE
remove_button_labels option

### PR DESCRIPTION
**Pull request by germanbisurgi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | 
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ✔️

### CODE REVIEW

**Comment by germanbisurgi** [comment]
- Added remove_button_labels option: if if true and iconLib is set only icons will be displayed in buttons
- fixes some errors in themes. Mostly missing if statements before changing properties or appending elements.
- added theme tests. This will work also for future theme changes (like right now)
- some icons where changed to make it more homogeneous overall and to distinct the buttons functions (eg delete last and delete all are different icons now)
- added horizontal icons for moving array elements with format tab
- fixes super Matriosca layouts (elements in elements in elements...). 
- all icon libs and themes where updated although some will be removed

**Comment by germanbisurgi** [comment]
@pmk65 for the first problem, the reason was that we had btn-groups with only one button. Now they the buttons are all in the btn-group. I needed to move the div because it was causing the border radius issues: There must be a button at the beginning and a button at the end.

The second problem is caused to display inline container. I added display block class in the spectre theme. Is the only theme that addresses button alignment

**Comment by pmk65** [comment]
@schmunk42 let's get this one merged ASAP, so we can adjust the themes to match the changes.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
