### PR TITLE
Fixed the console error when using describedBy

### PR DESCRIPTION
**Pull request by partikule**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #786
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by germanbisurgi** [comment]
it seems like you need to format your code with eslint and push again

**Comment by partikule** [comment]
... hope it will not be refused because of that....

**Comment by germanbisurgi** [comment]
yes it is [linting error](https://travis-ci.com/github/json-editor/json-editor/jobs/357580410). We use eslint to improve code quality and consistency.

Bildschirmfoto 2020-07-09 um 09 07 47

**Comment by partikule** [comment]
I see.
I will try to be eslint compliant for the next pull request but I have currently no time to pull again this one.
Sorry for that.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
