### PR TITLE
Child editors were incorrectly enabled when opted out.

### PR DESCRIPTION
**Pull request by jramstedt**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | 
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by schmunk42** [comment]
Looks good actually, but tests are failing.

**Comment by germanbisurgi** [comment]
@jramstedt: Hey, the fix works perfectly, i tested it on my local copy and improved the tests to check:
- if the opt-in checkbox is checked/unchecked correctly
- if the opt-in checkbox is enabled/disabled correctly
- if the editor input is enabled/disabled correctly

hier the code for the test. You can copy paste it

```
// if an editor type "object" is disabled, also the child editors opt-in controls will be disabled.

  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.string"] .json-editor-opt-in', 'checked'), false);
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.string"] .json-editor-opt-in', 'disabled'), false);
  assert.equal(await I.grabAttributeFrom('[name="root[string]"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.number"] .json-editor-opt-in', 'checked'), false);
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.number"] .json-editor-opt-in', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[name="root[object][number]"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.boolean"] .json-editor-opt-in', 'checked'), false);
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.boolean"] .json-editor-opt-in', 'disabled'), 'true');
  I.click('.get-value');
  assert.equal(await I.grabValueFrom('.value'), '{"number":0,"boolean":false}');

  // Opening and Closing "Edit JSON" should keep opt-in state.

  I.click('[data-schemapath="root"] .json-editor-btn-edit');
  I.click('[data-schemapath="root"] .json-editor-btn-edit');
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.string"] .json-editor-opt-in', 'checked'), false);
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.string"] .json-editor-opt-in', 'disabled'), false);
  assert.equal(await I.grabAttributeFrom('[name="root[string]"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.number"] .json-editor-opt-in', 'checked'), false);
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.number"] .json-editor-opt-in', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[name="root[object][number]"]', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.boolean"] .json-editor-opt-in', 'checked'), false);
  assert.equal(await I.grabAttributeFrom('[data-schemapath="root.object.boolean"] .json-editor-opt-in', 'disabled'), 'true');
  assert.equal(await I.grabAttributeFrom('[name="root[object][boolean]"]', 'disabled'), 'true');
  I.click('.get-value');
  assert.equal(await I.grabValueFrom('.value'), '{"number":0,"boolean":false}');
```

**Comment by jramstedt** [comment]
Thanks @germanbisurgi ! Tests pass now.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
