### PR TITLE
fix of issues #30 and #185

### PR DESCRIPTION
**Pull request by pmk65**
Fixes issue #185 error and adds an extra option to display array add buttons at the top of the list #30 

To make the buttons appear at the top of the list, set the option "**array_controls_top**" to **true**
If no option is set, it will default to the bottom position.

### CODE REVIEW

**Comment by schmunk42** [comment]
@pmk65 I'd like to add you to the team of this project - if you want to; your contributions are very valuable.
Please feel free to send me an e-mail to t.munk [at] herzogkommunikation.de

**Comment by taschmidt** [comment]
This option doesn't work for arrays with a "table" format. First off, unless I'm missing something, the docs don't make that obvious which should probably be remedied. Second, would it be possible to add this? I have a pretty big array and it's a pain to scroll all the way to the bottom to add a new item.

**Comment by schmunk42** [comment]
@taschmidt PRs are always welcome. Could you also provide a link to an example showing the issue?

**Comment by taschmidt** [comment]
Sure, [here's an example](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QBUAWEB2BzAziANOAJ4AO8SAhgE5UVEEgBmA9lQLYViLgUBGcDKLDZ4EoMKXIgcYKpiwgAvoqA===&value=NoIgLgFglgdg5iANOa8ktg5lPp27VLDAk4/covKw3W0i6usphml+y5xz1rt7ux4cRwsUImCpAmfzl8FvJaMmyFAXSA==&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&array_controls_top).

I was playing around in the code and had it pretty much working but I got distracted by other things. Actually, one of the things that bothered me (and this is the same behavior shown for other array formats that respect the "array controls at the top" setting) is that when you have a larger table and you click the new row button, you don't really get any visual feedback that it's done anything. This is because it's added a row way at the bottom which is well out of sight. Would it be acceptable to put a call to scrollIntoView in there or something?

**Comment by schmunk42** [comment]
> Actually, one of the things that bothered me (and this is the same behavior shown for other array formats that respect the "array controls at the top" setting) is that when you have a larger table and you click the new row button, you don't really get any visual feedback that it's done anything. This is because it's added a row way at the bottom which is well out of sight. Would it be acceptable to put a call to scrollIntoView in there or something?

But why don't leave them at the bottom then :)? 
It might also be annoying if you want to add, let's say, 5 rows quickly and you need to scroll up after every click.

**Comment by pmk65** [comment]
> 
> 
> This option doesn't work for arrays with a "table" format. First off, unless I'm missing something, the docs don't make that obvious which should probably be remedied. Second, would it be possible to add this? I have a pretty big array and it's a pain to scroll all the way to the bottom to add a new item.

@taschmidt This should be easy to fix. As the `table` editor extends the `array` editor. So all that is needed is to take the changes I made to the `array` editor and apply them to the `table` editor. (in the `build `function)

**Pull request merged**
