### PR TITLE
Bootstrap 5 - follows migration instructions on bootstrap site.

### PR DESCRIPTION
**Pull request by alvin**
#1009 

Initial port of bootstrap 5 with goal of low diff from bootstrap4 functionality and appearance.  Followed docs on bootstrap 5.2 website. 

* adds to tests/pages/themes.html
* also changes stepper and starrating docs examples to use bootstrap5 (but these reference the CDN production build of jsoneditor so I used ../dist/jsoneditor.js to test locally)
* Opinion: re-adds css for `.form-group` class with margin-bottom:1rem; (from bootstrap4 -- documented as removed bootstrap 5 so should not conflict).   Did this instead of hard-coding a bottom margin utility, which should continue to allow for easier theme overrides in user code (including backward compatibility for those who may already have done so targeting the bootstrap 4 class)

Initial visual tests seem to past decently 🎉  and feedback is welcome.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #1009
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by alvin** [comment]
Hi team - curious if there are any other quick things I can do to move this forward?

**Comment by germanbisurgi** [comment]
@alvin @schmunk42  It looks very good to me. For what i can see:
- The bootstrap4.js was used as the starting point to makes changes easier.
- The "Migrating to V5" page" changes reflected into the bootstrap5.js.
- Cleanup of commented out code is a plus.

It would be nice to update themes_test.js with the bootstra 5 case.

**Comment by robocoder** [comment]
Many docs/* default to bootstrap4. These should be updated to bootstrap5 (though not necessarily as part of this PR).

**Comment by alvin** [comment]
@germanbisurgi sounds good.  I just removed a few more lines of old legacy code and cloned the bootstrap4 test case in `themes_test.js` as per your suggestion.

@robocoder I agree -- (at least eventually) -- my original PR does include a couple of examples migrated, however I wanted to be cautious and not presume that this new theme is yet stable enough to become the de-facto default -- maybe wise to get it out for some usage/testing and feedback/fixes before moving all the docs over?

What do we think?  What would make this "good enough" to merge + release -- (perhaps initially with an "experimental" or "beta" designation?)  -- It does seem to me that signalling support for Bootstrap 5 is likely to help with broader adoption (if that is one of the goals of this community)

**Comment by germanbisurgi** [comment]
There are some linting errors. Could you fix this?

Bildschirmfoto 2022-11-10 um 09 57 21

**Comment by alvin** [comment]
@germanbisurgi done!

**Review by germanbisurgi — APPROVED** [review]

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
