### PR TITLE
new test page `array-anyof.html` without test case.

### PR DESCRIPTION
**Pull request by wclssdn**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ❌
| Fixed issues  | test case for #459 
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by pmk65** [comment]
@wclssdn Can you make a test case for it?
I have added a CodeceptJS/Puppeteer setup in the develop/2.x branch. So now you can run tests without having to install Docker.

**Comment by wclssdn** [comment]
@pmk65 I can run testes in Docker, but i never wrote test case. 😅😅😅
And for now, the test will be failed...

**Comment by schmunk42** [comment]
@wclssdn It would be OK, if the test fail - actually they have to fail, since it's a bug atm. Just mark them with `@optional` in the name at the end.

It can be very minimal, just to see the issue.

**Comment by pmk65** [comment]
> I can run testes in Docker, but i had never written a test case. 😅😅😅

@pmk65 I can run testes in Docker, but i had never written a test case. 😅😅😅

Me neither. But after setting up CodeceptJS/Puppeteer I discovered that it is actually very easy, and the test functions pretty much explains themselves.

**Comment by sirockin** [comment]
I'm gonna second @pmk65 on the issue of test cases. It's really the most reliable way each feature:

1. Is properly specified
2. Is well understood
3. Does not get broken accidentally as the code is maintainted

**Comment by wclssdn** [comment]
OK, i'll try to write a test case for this.

**Comment by schmunk42** [comment]
I going to merge this to have a minimal amount of PRs open for #546, test case comes later.

**Pull request merged**
