### PR TITLE
test case for page `array-anyof.html`

### PR DESCRIPTION
**Pull request by wclssdn**
test case for page `array-anyof.html` 

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ❌
| Fixed issues  | Test case for #459 
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

It doesn't work correctly, i don't know why.

```
  I.clearField('root[items][0][id]');
  I.click('.get-value');
  I.seeInField('root[items][0][id]', '');
  // todo: why this passed?
  let r = I.see('Value must match the pattern ^[a-zA-Z0-9_]+$.');
  assert.equal(r, true, 'it should appear');
```
It should be failed(when i operate on browser manually it didn't display a warning).
Please help.

### CODE REVIEW

**Comment by schmunk42** [comment]
@germanbisurgi Could you have a look?

**Comment by pmk65** [comment]
@wclssdn Try changing

```
 let r = I.see('Value must match the pattern ^[a-zA-Z0-9_]+$.');
 assert.equal(r, true, 'it should appear');
```

To

`assert.equal(await I.see('Value must match the pattern ^[a-zA-Z0-9_]+$.'), true, 'it should appear');`

**Comment by wclssdn** [comment]
@pmk65 I change to that, it's still not work. I don't know why...

**Comment by pmk65** [comment]
> 
> 
> @pmk65 I change to that, it's still not work. I don't know why...

There's currently a problem with the CodeceptJS tests due to some changes in the recent versions. So all tests fail in Firefox. 
Same with this PR. It passes in Chrome, but fails in Firefox. So your code might be working fine (Otherwise it should fail in Chrome too.)

**Comment by pmk65** [comment]
Test passed now.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
