### PR TITLE
Mention DomPurify in Upgrading

### PR DESCRIPTION
**Pull request by hungerburg**
HTML no longer passed in descriptions @see #83155ea

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks backward-compatibility?    | ✔️/❌
| Tests pass?   | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ✔️/❌
| Added CHANGELOG entry?   | ✔️/❌

### CODE REVIEW

**Comment by schmunk42** [comment]
How about including DomPurify as a dependency (also for webpack)?

CC: @pmk65 @germanbisurgi @amk0

**Comment by pmk65** [comment]
> 
> 
> How about including DomPurify as a dependency (also for webpack)?
> 
> CC: @pmk65 @germanbisurgi @amk0

It's not optional, not required. If you don't need to include HTML in the header/description, you don't need it.

**Comment by schmunk42** [comment]
> How about including DomPurify as a dependency (also for webpack)?

That was meant as documentation (how-to), instead of loading it from "some CDN".

**Comment by hungerburg** [comment]
I myself did download the zip and put it on my server; For the PR I just did echo the include from the main intro page. Such is getting more and more complicated, but the old farts work around with ever more effort.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
