### PR TITLE
Added filter to remove duplicate error messages

### PR DESCRIPTION
**Pull request by pmk65**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by pmk65** [comment]
Included in the #472, so I'll just close this one.

**Comment by schmunk42** [comment]
In which cases do we get duplicate error messages?

**Comment by pmk65** [comment]
Example: https://is.gd/XlkkI8

**Comment by schmunk42** [comment]
```
Value must not validate against the provided schema

Value must not validate against the provided schema
```

Which values/properties are causing the two errors?
Shouldn't that read "Value does not validate..."?

**Comment by pmk65** [comment]
I don't know, but there's 4 "not" properties in the schema, so my guess it's one of them. (I rarely use `not`, `oneOf`, `anyOf `, as I don't like the output with the oddly placed selectboxes 😁 )

**Pull request closed without merging**
