### PR TITLE
Default value in select from schema property

### PR DESCRIPTION
**Pull request by danyaridiger**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  |  #1566
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by danyaridiger** [comment]
Please restart the tests, locally all tests run correctly.

**Comment by schmunk42** [comment]
@germanbisurgi Please have a look.

**Comment by germanbisurgi** [comment]
I think this was solved in this PR #1565

**Comment by danyaridiger** [comment]
Seems like not because default value still doesn't substitute from 'property' fields (if it's there).

**Comment by germanbisurgi** [comment]
@danyaridiger could you open an issue with the steps to reproduce the bug?

**Comment by germanbisurgi** [comment]
probably related -> [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAMTmJ0clHa90C6EIqAA2iBfFB7iIwG17lQYOQBqMsNAYJJ7mBOpEQABdNhiIYqdEoECY7EAXzYFOIJyoYHJ0PwEAALCBWaygA)

**Comment by danyaridiger** [comment]
Then how to correctly specify the initial value for the select?

**Comment by danyaridiger** [comment]
String and other properties always substitute from "property" field

**Comment by germanbisurgi** [comment]
To specify the initial value of an editor the `default` keyword is used like in this [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOAAVIohKmwYnMTmAni8oPdhABHdAwYQDFAAbRAbUCYnIIAAutVOHMojBFmhCogAPLwLBgkBIjkoEBUMBgST4eAgAC+bFJ8HJnO5J0clHa90C6EIqGJ/w5bH4IK0mvAnUiVNF4vYtPm0U5MFZ7JkKTkkulvLABopxsRfWIJ35zvl+AgABYxaKgA=)

**Comment by schmunk42** [comment]
> This is fine, but why are strings and other primitives replaced from the property, but the selections/radios/checkboxes were not?

@danyaridiger Could you create an example for that I do not really understand what you mean.

**Comment by danyaridiger** [comment]
> > This is fine, but why are strings and other primitives replaced from the property, but the selections/radios/checkboxes were not?
> 
> @danyaridiger Could you create an example for that I do not really understand what you mean.

I couldn't reproduce this. Seems like @germanbisurgi is right and it was fixed in v2.15.1.

**Comment by danyaridiger** [comment]
Sorry for this maychem)

**Pull request closed without merging**
