### PR TITLE
Cybtachyon cybtachyon/988  json pointers

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #988 
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ✔️

PR from https://github.com/json-editor/json-editor/pull/994 with hardened test

### CODE REVIEW

**Review by germanbisurgi — COMMENTED** [review]
@cybtachyon great job!

**Review by germanbisurgi — DISMISSED** [review]

**Comment by germanbisurgi** [comment]
I have noticed that there is a test page named references.hmlt but I have not found any test that uses this page.
I opened the page manually and saw that the references work but I think we should automate a test to make sure we don't break it in the future

**Review by germanbisurgi — APPROVED** [review]
I did not find any problems when manual testing this so i think we can merge the PR. I can write a test for this afterwards just to prevent that it not breaks in the future.

**Comment by schmunk42** [comment]
@cybtachyon @germanbisurgi Thank you!

**Pull request merged**
