### PR TITLE
Default array format to table if no format specified

### LINKED ISSUE #837: Improvement: Make array format configurable and/or default to table format
### General information

- json-editor version: _2.4.0_

I am aiming to use JSON Editor without needing to include properties related to formatting within the JSON Schema instance (for my use case the instance needs to contain only data, not information about how to display that data), but in order to get array input to display in JSON Editor, it must have the key/value pair `"format": "table"` included in the instance.

### Actual behavior

When you leave it out, you get this (note the missing input field, row label and button):

image

### Expected behavior

But when you add the `"format": "table"` key/value pair it displays correctly:

image

### Steps to reproduce the behavior

You can try this yourself by going to the interactive editor:  
https://json-editor.github.io/json-editor/

Then scroll down to replace the default schema instance with the instance below, then click Update Schema. Reload the page and try it with and without the `format` key/value pair included.

```json
{
    "type": "object",
    "title": "Test of Array without Format key",
    "properties": {
        "linked_schemas": {
            "title": "Linked Schemas",
            "description": "The schemaIds against which the profile must be validated",
            "type": "array",
            "format": "table",
            "items": {
                "type": "string",
                "pattern": "[A-Fa-f0-9]{64}"
            },
            "minItems": 1,
            "maxItems": 10,
            "uniqueItems": true
        }
    }
}
```

### Possible solutions

There are two possible solutions I can think of to fix/improve this:

1. Automatically assume `format` is `table` for an array as a default if no `format` property is specified.
2. Add an `array_layout` configuration option, as is currently available for objects with `object_layout` (as noted in the README).

I took a look at the code and could not figure out where `format: table` for arrays was recognized and then processed, but if you can point me in the right direction, I would be glad to try to implement one of the above two solutions and create a PR, presuming you are happy to make this type of a change. I do think offering an option to remove a formatting property within a schema instance is a worthwhile improvement.

Thanks in advance for considering this suggestion.

### PR DESCRIPTION
**Pull request by geoffturk**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | Resolves #837 
| Updated README/docs?   | ❌ (maybe consider removing `format: table` from README examples and demos in `/docs`)
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Review by schmunk42 — CHANGES_REQUESTED** [review]
Several tests fail.

**Comment by geoffturk** [comment]
Understood. I moved the location of the check but there is still one Selenium test failing.

I just realized however that this change will actually break backward compatibility for anyone with a schema instance who is assuming that the implied format of `multiselect` will be enabled because they have not specified a value for the array's `format` property.

**Comment by schmunk42** [comment]
I am not too keen on changing the defaults.

@germanbisurgi @marc7000 ?

**Comment by geoffturk** [comment]
Closing since already resolved by #843

**Pull request closed without merging**
