### PR TITLE
Base64 allow for custom input attributes

### PR DESCRIPTION
**Pull request by DCkQ6**
It could be handy in some cases

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | --
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by schmunk42** [comment]
Can't this be done in the schema?

CC: @germanbisurgi

**Comment by DCkQ6** [comment]
No, it cannot be done with the current schema. The schema looks like this:

```javascript
{
  'title': 'Media Custom Attributes Support',
  'type': 'object',
  'properties': {
    'media': {
      'type': 'string',
      'media': {
        'binaryEncoding': 'base64'
      },
      'options': {
        'inputAttributes': {
          'foo': 'bar'
        }
      }
    }
  }
}
```
This schema produces the following input element:

```html
<input type="hidden" class="form-control" value="">
```
Notice that there is no `foo` attribute present.

After implementing this pull request, the produced element looks like:

```html
<input type="hidden" class="form-control" foo="bar" value="">
```
This modification aligns with the behavior observed in other editors.

**Comment by germanbisurgi** [comment]
The base64 has two inputs: a hidden input and a file input. Currently, the setInputAttributes method sets attributes in the hidden input since it's the one stored in "this.input". The method could be enhanced to optionally specify the input used.

```javascript
// base64.js
this.setInputAttributes(['multiple'], uploadButton)
```

```javascript
// editor.js
setInputAttributes (inputAttribute, input) {
  if (this.schema.options && this.schema.options.inputAttributes) {
    const inputAttributes = this.schema.options.inputAttributes
    const protectedAttributes = ['name', 'type'].concat(inputAttribute)
    const workingInput = input || this.input
    Object.keys(inputAttributes).forEach(key => {
      if (!protectedAttributes.includes(key.toLowerCase())) {
        workingInput.setAttribute(key, inputAttributes[key])
      }
    })
  }
}
```

**Review by germanbisurgi — CHANGES_REQUESTED** [review]
By passing the array into the method every item in t

**Review by germanbisurgi — APPROVED** [review]

**Pull request merged**
