### PR TITLE
Solve Issue #214

### PR DESCRIPTION
**Pull request by pmadril**
- Solve issues about rendering HTML
- Solve simple Materialize problems. Materialize doesn't include tabs-top and categories support. I will add this on a next PR.

### CODE REVIEW

**Comment by pmadril** [comment]
Do not merge. Is not working.

**Comment by pmadril** [comment]
Sorry again, I really need somebody else than not me testing this. It seems that everything is ok and my test environment had problems.

**Comment by pmk65** [comment]
Worked for me during a quick test using bootstrap4. Will test using a more complex setup (Anyone got a good test case?)
Only problem I noticed was that the 1st tab wasn't active after load.

**Comment by pmk65** [comment]
@schmunk42 I tested this a bit more and found no errors. Looks like @pmadril got all themes except Materialize to work. (He mentioned that in the PR text).
So I think it's safe to merge. 😉

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
