### PR TITLE
Added support for Materialize CSS and Material Icons.

### PR DESCRIPTION
**Pull request by patrickberger**

### CODE REVIEW

**Comment by schmunk42** [comment]
> Replace EpicEditor with SimpleMDE

Is EpicEditor deprecated or why is it removed?

**Comment by patrickberger** [comment]
The replacement of EpicEditor by SimpleMDE was done in master branch. Maybe @fenichelar could enlighten us.

**Comment by fenichelar** [comment]
@schmunk42 @patrickberger SimpleMDE includes a toolbar to make it easy for people who don't know markdown to write markdown, EpicEditor does not. I think it makes sense to have a toolbar because json-editor makes it easy for people who don't know JSON to write JSON.

**Comment by schmunk42** [comment]
I haven't looked to deep into the code, but ideally we can add editors via https://github.com/dmstr-forks/jdorn-json-editor#custom-editor-interfaces instead of having `if` statements in the code.

While we can deprecate features here and there, we should be able to maintain BC.

Would it be possible to remove EpicEditor and SimpleMDE from the core and add it via custom editor interfaces?

**Comment by fenichelar** [comment]
It's been awhile since I looked at json-editor (over a year), but if I recall correctly, I made a simple swap from EpicEditor to SimpleMDE because SimpleMDE has a toolbar and there was a bug with EpicEditor when the data was undefined. See https://github.com/jdorn/json-editor/pull/667.

It looks like this is a fork of a fork of a fork so I am not sure how my commit got here. I think that this PR should be limited in scope as much as possible.

@schmunk42 As far as removing EpicEditor and SimpleMDE, again, I think that should be separated from this PR as it is out of scope.

@patrickberger Can you remove my commits from this PR? It looks like they were already merged in this fork anyways.

**Comment by patrickberger** [comment]
@fenichelar, @schmunk42 I removed my merge from master. Could you please check if this is ok? I am new to git and it took me some time and reading.

**Comment by schmunk42** [comment]
I've merged several PRs on `develop` - I think we have to remove the `dist` folder on development (master) branches and only include `dist` files for releases. Otherwise it's practially impossible to handle merges.

CC: @loganvolkers @xvaara @jdorn WDYT?

**Pull request merged**
