### PR TITLE
Fix relative $ref issue discussed in #923

### PR DESCRIPTION
**Pull request by robocoder**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Is backward-compatible?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #923
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by schmunk42** [comment]
@robocoder 

Could you update this PR with `master`, please.

I've switched to GitHub actions, since Travis failed too often due to missing credits. And now GH-actions must pass.

Sorry for the inconvenience.

**Review by schmunk42 — APPROVED** [review]

**Comment by schmunk42** [comment]
@robocoder I tried to update this PR with `master` but the GH-action don't start?!

**Comment by robocoder** [comment]
I haven't switched to GH actions in any of my repos yet. Let us know what you learn. ;)

**Comment by schmunk42** [comment]
> I haven't switched to GH actions in any of my repos yet. Let us know what you learn. ;)

This :) https://github.com/json-editor/json-editor/pull/963/files
I hope.

**Comment by schmunk42** [comment]
@robocoder please one more try, thanks

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
