### PR TITLE
fix multiple choice checkbox issue (minItems)

### PR DESCRIPTION
**Pull request by Tysiana**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Is backward-compatible?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #909
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Review by schmunk42 — APPROVED** [review]
@germanbisurgi Please have a second look.

**Comment by schmunk42** [comment]
@Tysiana Is this really not backward-compatible? Could you update the PR with master, please.

**Review by schmunk42 — CHANGES_REQUESTED** [review]
Merge conflicts, see also conversation.

**Comment by Tysiana** [comment]
> @Tysiana Is this really not backward-compatible? Could you update the PR with master, please.

Hi. This PR can be rejected. From what I gathered the issue is resolved by [36f5e7d](https://github.com/json-editor/json-editor/commit/36f5e7dc6ff06806c7f0b00b1473d5816d89bd1c) Thanks

**Pull request closed without merging**
