### PR TITLE
Uploadrefactor3

### PR DESCRIPTION
**Pull request by pmk65**
- Now uses custom button to trigger upload
- Now supports upload via Drag&Drop
- Activation/configuration now uses the new options/callback methods introduced in 2.x
- Various config options added
- Now upload can be restricted to specific mime type(s)
- DropZone added
- Minor bugs/issues fixed

ToDo:
- Figure out a good layout of all the element present in the container
- Move Style Rules to theme
- Create necessary theme functions for customizing

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks backward-compatibility?    | ✔️ (Config options have changed, output is identical)
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by pmk65** [comment]
@schmunk42 I can also create a NEW additional upload editor if you are unsure about the changes?

**Comment by pmk65** [comment]
**Test Schema Data:**
````json
{
  "type": "object",
  "title": "Upload Editor Example",
  "properties": {
    "upload_default": {
      "type": "string",
      "format": "url",
      "title": "Default Upload field",
      "description": "No options set except for the <strong>uploadHandler</strong>",
      "options": {
        "upload": {
          "uploadHandler": "testUploadHandler"
        }
      },
      "links": [
        {
          "href": "{{self}}"
        }
      ]
    },
    "upload_custom_link": {
      "type": "string",
      "format": "url",
      "title": "Image Upload field",
      "description": "Upload restricted to JPEG and PNG image files. (Using custom link?)",
      "options": {
        "upload": {
          "mime_type": [
            "image/png",
            "image/jpeg"
          ],
          "uploadHandler": "testUploadHandler"
        }
      },
      "links": [
        {
          "href": "{{self}}",
          "rel": "view"
        }
      ]
    },
    "upload_readonly": {
      "readonly": true,
      "type": "string",
      "format": "url",
      "title": "Upload field (Read Only)",
      "description": "Property has already a value (from startval)",
      "options": {
        "upload": {
          "mime_type": [
            "image/png",
            "image/jpeg"
          ],
          "uploadHandler": "testUploadHandler"
        }
      },
      "links": [
        {
          "href": "{{self}}"
        }
      ]
    },
    "upload_drag_drop": {
      "type": "string",
      "format": "url",
      "title": "Drag&Drop Image Upload field",
      "description": "Drag&Drop with custom dropzone text (Upload restricted to image files.)",
      "options": {
        "upload": {
          "enable_drag_drop": true,
          "title": "Select image",
          "drop_zone_text": "Drag & Drop your image file here",
          "mime_type": "image/*",
          "uploadHandler": "testUploadHandler"
        }
      },
      "links": [
        {
          "href": "{{self}}"
        }
      ]
    },
    "upload_drag_drop_hidden_input": {
      "type": "string",
      "format": "url",
      "title": "Drag&Drop Upload field",
      "description": "Drag&Drop Upload with Button input hidden",
      "options": {
        "upload": {
          "hide_input": true,
          "enable_drag_drop": true,
          "uploadHandler": "testUploadHandler"
        }
      },
      "links": [
        {
          "href": "{{self}}"
        }
      ]
    },
    "alt_drop_zone": {
      "format": "info",
      "title": "Drag&Drop Upload alternate dropzone",
      "description": "<div id=\"alt-drop\" style=\"width:200px;height:200px;border:2px solid black;border-radius:50%;background:orange;\"></div>"
    },
    "upload_drag_drop_custom": {
      "type": "string",
      "format": "url",
      "title": "Drag&Drop Upload field",
      "description": "Drag&Drop Upload with alternate dropzone",
      "options": {
        "upload": {
          "alt_drop_zone_id": "alt-drop",
          "hide_input": true,
          "enable_drag_drop": true,
          "uploadHandler": "testUploadHandler"
        }
      },
      "links": [
        {
          "href": "{{self}}"
        }
      ]
    }
  }
}
````

**Test JavaScript setup:**
````javascript
// Specify upload handler
JSONEditor.defaults.callbacks.upload = {
  "testUploadHandler" : function(jseditor, type, file, cbs) {
    if (type === 'root.upload_fail') cbs.failure('Upload failed');
    else {
      var tick = 0;
  
      var tickFunction = function() {
        tick += 1;
        console.log('progress: ' + tick);
  
        if (tick < 100) {
          cbs.updateProgress(tick);
          window.setTimeout(tickFunction, 50);
        } else if (tick == 100) {
          cbs.updateProgress();
          window.setTimeout(tickFunction, 500);
        } else {
          cbs.success('http://www.example.com/images/' + file.name);
        }
      };
  
      window.setTimeout(tickFunction);
    }
  }
};
````

Note: DOMPurify library must be enabled/loaded.

**Comment by schmunk42** [comment]
> @schmunk42 I can also create a NEW (additional) upload editor if you are unsure about the changes?

Is this PR for a specifc plugin or more a general "interface" to attach custom plugins?

**Comment by pmk65** [comment]
> 
> 
> > @schmunk42 I can also create a NEW (additional) upload editor if you are unsure about the changes?
> 
> Is this PR for a specifc plugin or more a general "interface" to attach custom plugins?

It's a refactor of the existing Upload editor, adding more options, features and some minor fixes.

**Comment by schmunk42** [comment]
@pmk65 Is this ready to merge from your side?

**Comment by pmk65** [comment]
> 
> 
> @pmk65 Is this ready to merge from your side?

I'm trying to setup a live test example, but Github doesn't seem to be updating the preview page at the moment. (There's some layout issues which could be nice to fix first.) So wait a bit longer before merging until I have the live test page ready..

**Comment by pmk65** [comment]
@schmunk42 @germanbisurgi Finally Github updated the pages, so I managed to create a test setup: https://is.gd/Yupe8V

The test setup shows the upload editor with various options enabled. Like mimetype restrictions, dropzones etc.

We need to figure out a good way to organize all the various elements (button, file name, dropzone, preview (which contains file size/type info, link, upload button and thumbnail (if image upload) 

Currently the preview element replaces the description element, which I want to change.

Comments/ideas appreciated 😄

**Comment by pmk65** [comment]
Since there was no comments on the PR, I will move on to another refactoring issue.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
