### PR TITLE
better fix for 736

### PR DESCRIPTION
**Pull request by germanbisurgi**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #736
| Updated README/docs?   | ✔️/❌
| Added CHANGELOG entry?   | ✔️/❌

### CODE REVIEW

**Comment by schmunk42** [comment]
@odscjames WDYT?

**Comment by odscjames** [comment]
@schmunk42 From what I know of the system, that looks good in terms of Uniqueness. Thanks.

But also just noticed, innerHTML might contain spaces? Id's shouldn't contain spaces - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id Tho that page does note that "Browsers treat non-conforming IDs that contain white-space as if the white-space is part of the ID." so it may be ok, but personally I wouldn't want to rely on error behaviour like that when replacing spaces shouldn't be to hard to do.

**Comment by germanbisurgi** [comment]
i removed the label fragment

**Comment by odscjames** [comment]
Thanks :-)

**Comment by schmunk42** [comment]
@gbisurgi @odscjames so this is ready to merge?

**Comment by odscjames** [comment]
This does improve the current code and has tests which are good :-) I haven't tried to run it myself tho - in particular I note that this gives float values like "683012369529.4961" and I would want to double check that these were converted to matching strings correctly in the DOM.

**Pull request merged**
