### PR TITLE
Standardjs

### PR DESCRIPTION
**Pull request by sirockin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #546 
| Updated README/docs?   | ✔️
| Added CHANGELOG entry?   | ❌

Well that took some time! :-/

Obviously there are *a lot* of files changed. May I suggest reviewers focus on:
1. `package.json` - new scripts `eslint` and `eslint.fix`
1. `webpack.common.js` - changes to `eslint-loader rule`. In particular, do we want to keep `options.fix:true` or should we leave it to developers to run `npm run eslint.fix`?
1. `CONTRIBUTING.md` - updated stuff on coding style
1. Any lines starting with `// eslint-disable` - in those cases I disabled a rule because applying a standard fix broke the build and/or I was unsure how to fix

### CODE REVIEW

**Comment by germanbisurgi** [comment]
this is awesome :)

i would leave the ESLint fix out because the it will tell you if something is wrong right after saving changes. Also because we should not use that command in the CI

**Comment by sirockin** [comment]
> this is awesome :)

Thanks!

> i would leave the ESLint fix out because the it will tell you if something is wrong right after saving changes. Also because we should not use that command in the CI

Ah yes good point about the CI!.

**Comment by schmunk42** [comment]
Awesome, thank you very much!

PS: I removed the info about autofix, according to the comments above.

**Comment by sirockin** [comment]
> PS: I removed the info about autofix, according to the comments above.

Ah yes, thanks for spotting and removing!

**Pull request merged**
