### PR TITLE
Improved base64.js editor to be able to upload multiple files to multiple array items

### PR DESCRIPTION
**Pull request by ruud12**
It is desirable to be able to upload multiple files at once using the base64.js editor. The function has been altered to incorporate this functionality.

To be able to use the multiple upload functionality, the following requirement of the schema must be fulfilled:

- Property schema must include 'multiple: true'
- Parent object must be of type 'object'
- Parents parent object must be of type 'array'

When the above requirements have been fulfilled, the editor will

- Create new array item for each uploaded file
- Set the value of the added array item

Please correct my code whenever necessary.

### CODE REVIEW

**Comment by pmk65** [comment]
It would be great if you also could provide a working example in "docs/" folder. As info written in pull requests often get "lost" and this fork is missing the Wiki section.

**Comment by ruud12** [comment]
@pmk65: Apologies, I forgot the docs folder. I will add an extra pull request with information in the docs folder

**Comment by marc7000** [comment]
@ruud12: You can build your own dist files to test your feature. 
`npm run build`
Is everything ok, add a working example or update a example in "docs/" folder.

You can also run "dockerized" tests via `npm run docker-test`.

**Comment by ruud12** [comment]
I have added the example in the docs folder. At the moment the used json-editor.js file had been added as well for testing, but I suppose this should be removed after the functionality has been approved?

**Comment by pmk65** [comment]
@ruud12 What I did when I added my docs examples, was to test them out locally with the dist "json-editor.js" created by the Grunt task. Then after I had confirmed that everything worked correctly, I changed the JavaScript back to point at the original CDN version and committed the file.

**Comment by marc7000** [comment]
@pmk65: Thank you for the clarification and your support!

@ruud12: What have the "signature.js" to with the "base64.js" editor?
I think it's bette to split the PR, and also add a example and documentation update for the "signature.js" editor.

@pmk65: Did you have tested the multiple file upload successfully? What to you think about "signature.js" editor feature?

**Comment by ruud12** [comment]
@marc7000: You're right, the signature editor should not have been in this pull request. Appearantly i forgot to save it in a different branch. It is already working, but it is probably better to move it to a different pull request I suppose?

**Comment by marc7000** [comment]
Yes i think it's a cool feature. Separate it from this PR and make another PR with demo and documentation update.

**Comment by pmk65** [comment]
@marc7000 Yes. I tested the multiple file upload and from what I can see it works very well.
The signature editor looks interesting. By far the best result of drawing a signature using the mouse. (But mine still looks like crap 🤣)

**Comment by pmk65** [comment]
@ruud12 How do you handle the data returned from the base64 multiple uploads? (Guess the same question applies to single base64 uploads as well) As base64 data can get pretty big, especially if you got lots of it. 
It would be nice if there was some kind of preprocessing code that turns the base64 into binary before saving. (This would have to be some code outside the JSON-Editor, that handles the upload)

**Comment by ruud12** [comment]
@marc7000: I will split the signature editor tomorrow if i have the time and add a new pull request. 

@pmk65: At the moment I am planning to use the json-editor in combination with pouchDB and cordova as an offline app for the service engineers at my company (hence the signature functionality). I haven't really thought about how to cope with big files. I have tried putting multiple base64 (or blob) data files in pouchDB, and it does not seem to give any issues for files up to 10 MB (I haven't tried any larger files yet). As far as I know, the file has to be converted to blob or base64 by the browser anyway, as there is no other way to process it locally with pouchDB. But with html5 input file elements, the file is already converted to blob automatically I think, so it might be more logical to extend the regular select file editor

Both of you: thanks for the comments

**Comment by ruud12** [comment]
I have removed the signature editor. Are there any other changes required to the multiple upload functionality?

**Comment by pmk65** [comment]
@ruud12 I think that should be it. As the functionality already have been tested.

**Comment by ruud12** [comment]
@pmk65 You're right, I have removed those files

**Comment by marc7000** [comment]
Thank you!

**Pull request merged**
