### PR TITLE
Don't display checkbox label when inside object tables

### LINKED ISSUE #714: Checkboxes inside object tables duplicate labels from heading
### General information

Since b0c01c8, checkboxes inside object tables duplicate their labels from the heading, causing tables to be noisier (and slightly wider) than necessary

- json-editor version: 2.1.0

### Expected behavior
image

### Actual behavior
image

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIAILVaDAAIAYXoIMls2Xxp6KgCAOTAoYNDw8TYLKGQAXXSpSENYGg0fPxjkujDbNBAzC0I8MDAdMhM2EhkycSsVbgBrBoAPBUhYBGRqrArU1CgpESoAXwXI0sCEpJCpqs1zSxAGpqoWhXbZLpAejH6wIbYRuCRiycquojlEReWQDPGduqsyFIpEITtIzoRyHgdKYYNo9gZMgoRPAYE4qABJKBqcazeZsWHY4q1PZgTjcNI1WHQqwIhQQPIWKSFX41XZEtlWRCzGDwADmCio8BEdE8F06ClcYH5bDwLncbHs0Bg0LuUFUUhAORAriobxE2HOkv5X3gZAY7P+im5fJAXyi/liPICAHkyTwAgAVMhQyx/PYHZqtYhg8XdVRXQa2pZsHV6g2eP2EI0KU3mqzeW0sRNWZNsVN7ABCmez2qlKbNeyCxdZltzIHzhAAItXiUmy3mK4QAKK2rJLL6IZRgCi8Qx5IyEHlY4E8B6mVRp/aNTKzMgQAAsUaAA=

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "Awesome Compact",
    "Awesome Not Compact",
    "pets"
  ],
  "properties": {
    "Awesome Compact": {
      "type": "boolean",
      "format": "checkbox",
      "options": {
        "compact": true
      }
    },
    "Awesome Not Compact": {
      "type": "boolean",
      "format": "checkbox",
      "options": {
        "compact": false
      }
    },
    "pets": {
      "type": "array",
      "format": "table",
      "title": "Pets",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "cat",
              "dog",
              "bird",
              "reptile",
              "other"
            ],
            "default": "dog"
          },
          "name": {
            "type": "string"
          },
          "Awesome in Object Table": {
            "type": "boolean",
            "format": "checkbox"
          }
        }
      },
      "default": [
        {
          "type": "dog",
          "name": "A"
        },
        {
          "type": "dog",
          "name": "B"
        },
        {
          "type": "dog",
          "name": "C"
        },
        {
          "type": "dog",
          "name": "D"
        },
        {
          "type": "dog",
          "name": "E"
        }
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by JElchison**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #714
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ✔️

This PR fixes #714 by testing [the same logic used by `object.js`](https://github.com/json-editor/json-editor/blob/cfec910d219082995149babc7d65c3fe926f01bd/src/editors/object.js#L378), which is `this.options.table_row`.

Unit test result:
```
Chrome 81.0.4044 (Linux 0.0.0): Executed 164 of 164 SUCCESS (3.865 secs / 2.715 secs)
TOTAL: 164 SUCCESS
```

Unit test machine:
```
$ uname -a
Linux xxxxxxxx 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

@pmk65 would be a good reviewer of this PR since he was the committer of b0c01c8.

### CODE REVIEW

**Comment by schmunk42** [comment]
Shouldn't that be handled with the `compact` option, how it was before?

https://github.com/json-editor/json-editor/commit/b0c01c811c09628d82e89aeb9135a652940b8710#commitcomment-38297819

CC: @pmk65

**Comment by schmunk42** [comment]
@JElchison Are there test for the label in checkbox-lists and tables? Would be good to have them.

**Comment by JElchison** [comment]
Thanks for the review, @schmunk42!

I'm happy to implement this either way. I imagine that @pmk65 committed b0c01c8 in the first place to ensure that all top-level checkboxes (i.e. those not in an object)--even compact ones--would still have a label.

I'll illustrate using the [test schema](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIAILVaDAAIAYXoIMls2Xxp6KgCAOTAoYNDw8TYLKGQAXXSpSENYGg0fPxjkujDbNBAzC0I8MDAdMhM2EhkycSsVbgBrBoAPBUhYBGRqrArU1CgpESoAXwXI0sCEpJCpqs1zSxAGpqoWhXbZLpAejH6wIbYRuCRiycquojlEReWQDPGduqsyFIpEITtIzoRyHgdKYYNo9gZMgoRPAYE4qABJKBqcazeZsWHY4q1PZgTjcNI1WHQqwIhQQPIWKSFX41XZEtlWRCzGDwADmCio8BEdE8F06ClcYH5bDwLncbHs0Bg0LuUFUUhAORAriobxE2HOkv5X3gZAY7P+im5fJAXyi/liPICAHkyTwAgAVMhQyx/PYHZqtYhg8XdVRXQa2pZsHV6g2eP2EI0KU3mqzeW0sRNWZNsVN7ABCmez2qlKbNeyCxdZltzIHzhAAItXiUmy3mK4QAKK2rJLL6IZRgCi8Qx5IyEHlY4E8B6mVRp/aNTKzMgQAAsUaAA=) I used in #714...

Before b0c01c8 (keying off of `this.options.compact`).  Note missing checkbox label for first checkbox:
image

After b0c01c8 (always displaying checkbox label).  Note repeated labels in table:
image

What I believe to be expected behavior (keying off of `this.parent.options.table_row`):
image

Please let me know whether you and @pmk65 prefer that I key off of `this.options.compact` or `this.parent.options.table_row` to implement this fix.

I'm also happy to try my hand writing a test for this.  Thanks!

**Comment by JElchison** [comment]
FYI I've added a checkbox label test as part of this PR.  I'm still awaiting direction on whether to key off of `this.options.compact` or `this.parent.options.table_row` to implement this fix.  Thanks!

**Comment by germanbisurgi** [comment]
I played with JElchison:fix-checkbox-labels branch and tried different scenarios like nested arrays with same and different formats. I looks good to me. It is a good and is also an elegant solution given that its something like +3 line of code and 100+ of tests.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
