### PR TITLE
choose the best fit schema in the oneOf

### PR DESCRIPTION
**Pull request by wclssdn**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #128 #444

### CODE REVIEW

**Comment by schmunk42** [comment]
Thank you!

**Comment by wclssdn** [comment]
> Thank you!

My pleasure~

**Comment by pmk65** [comment]
@schmunk42 Could you merge this PR into the develop/2.x branch?

**Comment by wclssdn** [comment]
> @schmunk42 Could you merge this PR into the develop/2.x branch?

It's already merged. I have already checked.

**Comment by Vafa-Andalibi** [comment]
Hi, I still have the problem (@wclssdn) and I can't find what I'm missing. This is the schema I'm using: 

```input_schema = {
    type: "array",
    title: "IN",
    format: "tabs",
    items: {
        title: "InputGroup",
        headerTemplate: "Group{{i}} - {{self.neuron_type}}",
        oneOf: [
            {
                "title": "Video Input",
                "type": "object",
                "id": "video",
                "properties": {
                    "idx": {
                        "type": "integer",
                        "description": "Duration of simulation in miliseconds",
                        "default": "{{i}}",
                    },
                    "path": {
                        "type": "string",
                        "description": "Defines path to input video",
                    },
                    "type": {
                        "type": "string",
                        "description": "Defines path to input video",
                        "enum": ["Video"]
                    },
                    "freq": {
                        "type": "string",
                        "format": "text",
                        "description": "defines the frequency of "
                    },
                    "monitors": {
                        "type": "string",
                        "format": "text",
                        "description": "defines noise",
                    }
                }
            },
            {
                "title": "VPM",
                "type": "object",
                "id": "vpm",
                "properties": {
                    "idx": {
                        "type": "integer",
                        "description": "Duration of simulation in miliseconds",
                        "default": "{{i}}",
                    },
                    "type": {
                        "type": "string",
                        "description": "Defines path to input video",
                        "enum": ["VPM"]
                    },
                    "number_of_neurons": {
                        "type": "integer",
                        "description": "Defines number of neurons in neuron group ",
                        "default": 100,
                        "minimum": 1,
                        "maximum": 10000,
                    },
                    "radius": {
                        "type": "string",
                        "description": "defines",
                    },
                    "spike_times": {
                        "type": "string",
                        "description": "Defines the spike times ",
                    },
                    "net_center": {
                        "type": "string",
                        "description": "net center ",
                    },
                    "monitors": {
                        "type": "string",
                        "format": "text",
                        "description": "defines noise",
                    }
                }
            }
        ]
    }
}
```

and this is the input: 

```
var starting_value_inputs = [
    {
        idx: 1,
        type: "VPM",
        number_of_neurons: 60,
        radius: "92*um",
        spike_times: "[0.5]*second",
        net_center: "--",
        monitors: "[Sp]",
    }
];

var inputs_editor = new JSONEditor(document.getElementById('inputs_holder'), {
    ajax: true,
    schema: input_schema,
    startval: starting_value_inputs,
    no_additional_properties: true,
    required_by_default: true,
    disable_properties: true,
    disable_collapse: true
});
```

But although the input is of the second type in "oneOf", I'm still getting that categorized as the first. This is the screenshot of what I get: 

image


Any help would be highly appreciated.

**Comment by wclssdn** [comment]
@Vafa-Andalibi I suggest you use `anyOf`.

**Comment by coderofsalvation** [comment]
this might be related to https://github.com/json-editor/json-editor/issues/598 (issue happens for both oneOf + anyOf)

**Pull request merged**
