### PR TITLE
Update colorpicker.js

### PR DESCRIPTION
**Pull request by pmk65**
- Added support for 'setValue'   
- Added better enable/disable methods.
- Removed "onChange" function from list of required options so it can be overidden using schema options.
- Changed the update method (Otherwise buttons have no meaning). Now updating is done in "onDone" function, except if inline element. Then updating is done using "onChange" function.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks backward-compatibility?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ✔️

### CODE REVIEW

**Comment by pmk65** [comment]
@hybtalented what do you say to my changes?
Maybe the default updating (onChange/onDone) should be a schema option?

**Comment by schmunk42** [comment]
Looks good to me, but I am not to deep into this feature.

But we need to fix the tests before merging fixes and updates.

**Comment by pmk65** [comment]
> 
> 
> Looks good to me, but I am not to deep into this feature.
> 
> But we need to fix the tests before merging fixes and updates.

The tests is fixed in my other PR #630

**Comment by schmunk42** [comment]
I merged the other PR, but this one fails with a "real" error :)
https://travis-ci.org/json-editor/json-editor/jobs/624239608#L922

**Comment by pmk65** [comment]
@schmunk42 I have fixed the test that failed.

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
