### PR TITLE
format grid-strict

### PR DESCRIPTION
**Pull request by germanbisurgi**
Allows to set grid_size, grid_offset and grid_break

### CODE REVIEW

**Comment by germanbisurgi** [comment]
###New changes
opt-in for non required properties: when opt-in-optional-properties = true, getValue will take only the required values. Optional properties can be "opt-in" checking a checkbox and taken into account when gettig the value.

**Comment by germanbisurgi** [comment]
Hi, here are some screenshots of the json-editor implementing grid-strict

`
{
    "type": "object",
    "title": "range",
    "format": "grid-strict",
    "properties": {
      "a": {
        "title": "a",
        "type": "string",
        "options": {
          "grid_columns": 1
        }
      },
      "b": {
        "title": "b",
        "type": "string",
        "options": {
          "grid_columns": 2
        }
      },
      "c": {
        "title": "c",
        "type": "string",
        "options": {
          "grid_columns": 3
        }
      },
      "d": {
        "title": "d",
        "type": "string",
        "options": {
          "grid_columns": 4
        }
      },
      "e": {
        "title": "e",
        "type": "string",
        "options": {
          "grid_columns": 5
        }
      },
      "f": {
        "title": "f",
        "type": "string",
        "options": {
          "grid_columns": 6
        }
      },
      "g": {
        "title": "g",
        "type": "string",
        "options": {
          "grid_columns": 7
        }
      },
      "h": {
        "title": "h",
        "type": "string",
        "options": {
          "grid_columns": 8
        }
      },
      "i": {
        "title": "i",
        "type": "string",
        "options": {
          "grid_columns": 9
        }
      },
      "j": {
        "title": "j",
        "type": "string",
        "options": {
          "grid_columns": 10
        }
      },
      "k": {
        "title": "k",
        "type": "string",
        "options": {
          "grid_columns": 11
        }
      },
      "l": {
        "title": "l",
        "type": "string",
        "options": {
          "grid_columns": 12,
          "grid_break": true
        }
      },
      "m": {
        "title": "m",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1
        }
      },
      "n": {
        "title": "n",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 1
        }
      },
      "o": {
        "title": "o",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 2
        }
      },
      "p": {
        "title": "p",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 3
        }
      },
      "q": {
        "title": "q",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 4
        }
      },
      "r": {
        "title": "r",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 5
        }
      },
      "s": {
        "title": "s",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 6
        }
      },
      "t": {
        "title": "t",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 7
        }
      },
      "u": {
        "title": "u",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 8
        }
      },
      "v": {
        "title": "v",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 9
        }
      },
      "w": {
        "title": "w",
        "type": "string",
        "options": {
          "grid_break": true,
          "grid_columns": 1,
          "grid_offset": 10
        }
      },
      "x": {
        "title": "x",
        "type": "string",
        "options": {
          "grid_columns": 1,
          "grid_offset": 11
        }
      }
    }
  }
`

Bildschirmfoto 2019-05-10 um 11 08 05

Bildschirmfoto 2019-05-10 um 11 08 17



And here screnshots of the json-editor using opt-in-optionals-properties (shorter name ideas are wellcome)

`
{
    "title": "Data Types",
    "type": "object",
    "format": "grid-strict",
    "required": [
      "number",
      "boolean",
    ],
    "properties": {
      "string": {
        "title": "string",
        "type": "string",
        "minLength": 5,
        "options": {
          "grid_columns": 4
        }
      },
      "number": {
        "title": "number",
        "type": "number",
        "options": {
          "grid_columns": 4
        }
      },
      "boolean": {
        "title": "boolean",
        "type": "boolean",
        "options": {
          "grid_columns": 4,
          "grid_break": true
        }
      },
      "array": {
        "title": "array",
        "type": "array",
        "options": {
          "grid_columns": 6
        },
        "items": {
          "title": "string",
          "type": "string"
        }
      },
      "object": {
        "type": "object",
        "format": "grid-strict",
        "required": [
          "array",
          "string",
        ],
        "options": {
          "grid_columns": 6
        },
        "properties": {
          "string": {
            "title": "string",
            "type": "string",
            "options": {
              "grid_columns": 4
            }
          },
          "number": {
            "title": "number",
            "type": "number",
            "options": {
              "grid_columns": 4
            }
          },
          "boolean": {
            "title": "boolean",
            "type": "boolean",
            "options": {
              "grid_columns": 4
            }
          },
          "array": {
            "title": "array",
            "type": "array",
            "options": {
              "grid_columns": 12
            },
            "items": {
              "title": "string",
              "type": "string"
            }
          }
        }
      }
    }
  }
`

Bildschirmfoto 2019-05-10 um 11 09 25

Bildschirmfoto 2019-05-10 um 11 09 39

Bildschirmfoto 2019-05-10 um 11 10 02

**Comment by schmunk42** [comment]
@pmk65 Could you also have a look a this. 
We have reviewed and tested this internally and are quite happy with it.

**Comment by germanbisurgi** [comment]
yes, it uses underscores: `opt_in_optional_properties: true`

**Comment by schmunk42** [comment]
@germanbisurgi `opt_in_optional_properties` didn't we talk about another name for the setting?
@pmk65 Do you have a better proposal, it sounds somehow clumsy.

**Comment by pmk65** [comment]
> 
> 
> yes, it uses underscores: `opt_in_optional_properties: true`

@germanbisurgi Thanks. Got it working using "opt_in_optional_properties"
**Note:** "opt_in_optional_properties" is not mentioned in `README.md`

I also noticed a "strange" behavior if I turn on "display_required_only" in combination with "opt_in_optional_properties". Then only 2 fields are shown as default (Correct behavior)
When I in the "Properties" button, then turn on the remaining fields, the field is enabled but the checkbox is not checked. (I can make a screen capture video if you need to see it)

**Comment by pmk65** [comment]
> 
> 
> @pmk65 Do you have a better proposal, it sounds somehow clumsy.

`show_opt_in`

**Comment by germanbisurgi** [comment]
oh Yeah , is super clumsy. `show_opt_in` is much better but i wish it was more clear what is does. I will take a look at the "display_required_only" asap

**Comment by germanbisurgi** [comment]
now is `show_opt_in`. I also fix the unwanted behavior. Now the property added through the "Properties" button is initially active ("opted in") and can be  deactivated ("opted out") afterwards.

**Comment by germanbisurgi** [comment]
Also fixed foundation 3 and 4 fixes into grid-strict ( issue #305 )

**Comment by schmunk42** [comment]
Great work. Thank you!

**Comment by pmk65** [comment]
@germanbisurgi Just noticed some weird behavior when using your last example with the new release.
Try enabling `Select2` and notice that the 2nd Boolean select box gets a the width of the entire form.
Happens when you use Bootstrap3/4 (But not Bootstrap 2)

**Pull request merged**
