### PR TITLE
Property names

### PR DESCRIPTION
**Pull request by robocoder**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks backward-compatibility?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #811
| Updated README/docs?   | ❌
| Added CHANGELOG entry?   | ❌

### CODE REVIEW

**Comment by schmunk42** [comment]
LGTM in general, tests are failing because of:

```
  1) Validations
542       test validations in validation.html:
543
544      expected number of elements (#output div) is 136, but found 148
545      + expected - actual
546
547      -148
548      +136
```

but since there are more validations now it would make sense to raise that number to `148`, could you double check this.

**Comment by robocoder** [comment]
I'm not running the full test suite but I'll take a look into bumping that.

In terms of functionality, I based the implementation on:
* http://json-schema.org/understanding-json-schema/reference/object.html#property-names (only mentions `pattern`)
* https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2019-09/propertyNames.json (which gives the boolean and maxLength variants)

**Comment by robocoder** [comment]
And `enum` comes from:
* http://json-schema.org/draft-06/json-schema-release-notes.html

**Comment by robocoder** [comment]
I didn't implement the anyOf behaviour as that has an open issue:
* https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/255

**Review by schmunk42 — APPROVED** [review]
LGTM

@marc7000 @germanbisurgi Please have a second look.

**Comment by germanbisurgi** [comment]
Even if the issue was about patternProperties this new feature can solve the same problem. Here we talk about implementing propertyNames which is only about property names as opposed to patternProperties which is about both property name and value.

I've read the code but I haven't tested it locally yet, but since it's a new feature, new tests have been added, and there are no Backward compatibilities breaks i would merge this and then improve in the future.

**Review by germanbisurgi — APPROVED** [review]

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
