### PR TITLE
Make the meta-schema.json example nicer to use

### PR DESCRIPTION
**Pull request by Franciman**
Hi, I am updating and fixing the meta-schema.json example schema so that it generates an easier to use meta-schema editor.

The development of this PR was sponsored by @IanMayo  of http://DeepBlueC.com.

### CODE REVIEW

**Comment by pmk65** [comment]
Nice work. 
I noticed an error when I tried the schema. Line 51 contains a duplicate key.
See [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbAJgUwGYEsKoC6oPYQM5wBc40Msw+AxgBaIC2AhgIIBOrjAnsaeeXJk4AHRMTiN2XOABpIfGHHroAkpgaFgRAIyyyfOFnU858hcAAkrFGOABiAPRI0GbHnz3qdJjJOmBWABtRTThPBkY4X3IAXyjo3X1gCABXAIDjPX5gIVYcEVZsRA0SKMTBEQzTRMQU+mIAbVKquBS0yMzTAF0mmHieihrkus1eKrNDemLRsbNy4KIW1PTgft7+vo6sp0ZUzEqZgWF5ilblhIPs3PzBAHlWJFZiLQAGdabYzI3EgCMcHCDGBB9okcnlEAVUEVgfI4NtdtC/MA5jZfv9EID2mMvs0kUcETDgINhkRGptEaiAUCVmTyN0adjEUT8YkJlNVllkSFgBT0VT2R8sedEcgcKwmHsRuzDhUufhMKx0ABzHw0sxMzSkmZZfCIIJUCVCi60RBUADWvwAHpiZnTBf1YSgdgEJSVVRROUQKDyMcBDYjQddOHcHk9XvT3nFDaF5Ur8XAA+DCmyaXA8q4CMysgmIVDJW7xhAhMlMAB9ADuqHgmBomcRHujCogyupWt6fpx6CLpboqEVNBd01b0vmDdjLdbDIuiAtQkB8BLPb7A/ZZTxXO9fPzUEnYzgZc4+FQ++brtbHLXC25f0p1q1Apm99MO6yIrFjGXbuHNjljeb7ZBVyJkG9zgsQABMzz/lk6okiuFBUP8ooqmesLvsEUGJPAaHYPQ6Fwahag4YgAC0AQ4FQjBnPhhJMKgVFbooeDVshQ5JEM3ygb61EcE2eEMUiuosVqAjTga1FqBamASOiQkXERsm7sAySsPRKHAGWiCIKaCk4ow+q4AQVAKkIYn8d8760GgQQ6YiVA2QSVAANSOfZiRUEIQiuVkCHIMgmleWYVD4DQEimWpQUaBhWyhQFFDwAAVoCio4LFcCIPFkXUeCARJalwDJTlTZ5YquQ4AAbtwXH8SFEDwEE5msJl1WMPgpq6qprEhRafFqf29AdcJwDoKgeWJUgo2MGVERVWpiVTdQxlhaxGV4HlQT4E1akBKg+CeTNrEBMk01RWYTBtVZPWsUwrCmvAOBllSJ0UOKOXfHl9AHgAjgNFw4N88UmtgZUmnls7UJRoPZaDir4N9oM0HtT3xpw1arftg2POjFysMk3yVUjlAtZtrHgzleXUBt5PXYI5Nw1jilypwh3E4N+BlX+4kVhz/Fld8C2oCZeUWv1eWcIwIvjmMtpVM+Zhws6tbuheo5FZL8iy896AADI1IqzF5oN9ZDRAaiKpxUWKMN9BDMQkFSpcYIFMBIaaGBACs6xQYojAWjrTb66ecnK8bpvm/bSgYNbxJ25+DuBsGnFEAAzGGdoptk75qKwVKB4pRs/mOFvAK+4o2FYZtWvTBLZrcIGY8nHv0l7uIyrnOIwZqJMxqr7LS0+zcwYOiKsorszBwXPduo+6vN/LH6GxeFAT9zg0187icvJ79rALh8CoNNbd1sHf0A/qXniPAe/ppRAAKgE5sUyCUTqRc15CyZqR6Q9B63KvNnB08nxb3TmoegQgcpqEVl+WU3d/7hk2NPScix6AcXrt/eM98kyZlTCZAyH8Lhv1zIfDshZizlkrAHb+edx6wNvA+AmnYyGLn7KPc8v9KC0LVmnNS05Zy1QXIgXsLCDZniVuwjcdCsT8mAdQ1uVDoK1AaNRWoqDJHyD7jPbeg97YjxEQvdhKjOLSKbtvOeUCW4jjYigoxJj04R1QFHcxRtDGY1fpg9e9d3YyJxEwC0DibZ6JxM49iYdY5rwTvXFO3jETW2dALIINxkBOODi48+ccgIROIEnRuUiEGRiiAYE2iAzZoKaBgx2WDAmJDTHg8xhD8GDUYaWCsVYaxVJ/pY5eaj+7USaQIoR89RHQMvF0rhMsCa8LnP0pcrCx7iOvLybp6tjHcJxGY9pq52HoFDpjaJBJ7GOI2WwyxqSq4AQqR48COTxnb18f44k8i5knJCa4+24S65ZNTjcuxux4mIESckgxLy0nvJdg3PZmz5iPIGIojUvSiklKWTADRfANZpVhcQlkoCGkdJsNs4pNi7xvDyZ8XQBTgAn0BnGBAjpdh3wqe/JR6d6lqM6O2cp1xGVHJwemHF/pMFcsxQ5f4OUhA6ngLMsRliJFjJ6fxPe+BGDfCCCWBCaRGBiqhXBJ5KIFk+gAQTBVSqVWICviWFaOdoWQt1WifVW4NaYR2saxAJYWVHKPvM21m4zwOqyFYeg5UXUMBMpwV1AqiFWuOTam8srNH8RypwHAxZJXDL/rFNUGLO6iIoCVSsSL1EAJWd82RWrY4d2opSs+sbkUQq2LShW7qpU2ErRKWtZg3VCp1VyFtILM7gggPSzlEbqIADoABUKaLBWCSVyBwThhq8o8Mabw1aYhFrlYpWcmAs4DvDXygkRse1nKzH27Og7EyCsjXAcdk7LDWFnY4FAC68FLq8NNQtU820UEYJfLABlb57sBdKvV3ri04isJ9ZIqArASsbam4AEgOD43tskDAkHECqCMJoeUyREBFxLu+GwUllWXUUroztUaYG/jytgTA1kuRr3zYAmIzcCODJLd+ThRdy38VzbB3uxKgGkvJYhqQ7SHRPzpYBuF6ddFNDZWU9JD9sEUtwW4Op0mKOBRFRq8Vk6jYyoNdRI1JGSyidDT+2DWnKOXkM/aw1TrTPmZLEgIIkDG3WvXCB/NbZjOOZVc51ziA1BmbSCWXIZZ90ca816nz24HOKqc5IUNQWQs5TlOF+6+ng52Z9Ql51ZnkvhcQKKMFkau22e86u3z8r/MurVaKnU2XPUxo/US2x0WKPooCbBfi5n80opY6Y+t7GgnB367GtFQ1sXmLwP8mdvWzzlfdIEY4cAADKy7jraooHehbcA51PpcC+sIK6jNbmW/4Oja3gBsCQ1AHAyAoCnZaumptmhv3Jbe3APbxAKCHecH+twr7wh3bE09MwbG/sCGdXF5jfBBs1cUqh1A6HMOTCA9GxZk3m4R3R1FmzhSdlpIOT1r5G6fE+3x5jrk+LEXHtOlbMnX6L5X3/QEancGp33svAD59wOXtLKm1Drn+cuP2x42pCbBNiP0Zl0qlmckFfEUwHkPKxozSWnJrqKlDPvJoWSgqXMAn4FCdRWSzIoQtsACEWqlo9ZYo97KEO/uvgEc9ynNBPwCC/RTc8PeVMW0E1b9loHyedxBqDMG/uNAsXABTQJNgcovcOkBF5oXJ6dpkzQOh7Zi+o3rnltSPMUBoJWJAOccOiE/R1jsVmM9x6o4Xe2IvLzKRGjj7e5hBei5oQX/DopS5cnb0L5utH6NdcbyM8XYT3HZ6IGBFnNL+ZqctXnvvzfZ8XPnwAFmAVojFDejbS/DioGbOei4o7R+fogVe3Hb4+ZoN25O42KSJOtpNrAqD29+hAebTKlsdsrsJ8NsHFwFEAoAP9lJv9vsp801qt4s4JLskQQ8uQABhHAMBIIC0SAz/GAvXTzS8E/LcSHQfQjLkYjRXQaPHG/XPEgigcjZbMwObAFGTbNPgJgg9VAy8DAggKSE2KAAANUolwyoPYPg2IPYIJFbxhxIze0RCv1w051vxxjwx22Hhv04Id04wL3UOWXoPNz0JgC0I5G4I2zwNIykPe0vCdyMKyEsyBwgAAwZSIW919wMIJEj2g1NQAKsMSHwAsLiylghzWRGwD0FSzT8KXkCIQOCLsPbU0xMP8JiOszUhYIW0iKiPICSLkjMOAAAHULI6B4AoAAAxSEAIWDEI7NeDUZeIsDLIjg+ovOPI3guUQETAIQkQ3MaooZOAhDL7AgqwuAGQpEWHIYqQy2CAZQugxojsTQ5o3I67GwKaQ6SwuYwg1Mf6XXXomol3NnPAZwodR+Z+NQjwvYjtHItSVY3DSVLI2ozhRYu8XY8QlA5YkvOYh43Q849g+HDYv4rIgEqwoE7NRHX4l4/w7afA1I1iY/QYiE6Qsgl0WQuXJ4zWaYm/MCBExIXxZQrEtEgwBYn4zrInAlXZYk/QuY31NSKyLOO43FJvSeKk7Elbd4mE/RTpR4ikpHRouAG4n/T4/ouo7k7ceokEmWPQsEs3CcE3VZREX7XvdhYUuUgkdI8xBU3nR9QHRdF7MHSqJfQEIMBbBvDUg7LU/nAgEHJgPU0fbeSiAIVgyfU0uwc047AXLbG0zvdOCAHAUbeU6dGwPnN0y0nvJfUFROI/FJYFQvGlSTBtbQZ4RMpfbaCAU0AnCrcQeEnRIkz+Y+bYqtGXPIlM7SIY1nRwo4lPE4n3M4tSS4oA4AKwZYdk6w+AnbakrIGgAMj4wnDhfvPQkYpEmwZSZYNskIuAKgdLdMsbJUrk7NdsuWe6CAMiH9ek1MP/R0zI0RHI+DXLYEl47coU2c4EyU0c+s3efeAAFXT37MPO+LnLawfCXzLCKJpxsPzKWk3VPV3RcKnLMBvW7K+LHAfNyRVMSDoB/XBAvODQgQFOnM5LvIaNVNXynPg1sNjhqXUxLzgDakQCEBLDm0exLH5KrKayniLnWRIEQNjn90SKotXkSKylqBLHH1Tz2LhKQ1gMUIwxvzv3rNGNl3WIuEYJvPz030mJQOdEsRYqCNFPs2oj41VX+CGAzAAv6Lp1CT2IoqgFmL6NJ2JB0rUjuUOW0EXzkuqnLxqGa2A1iwQPbOws0jwoIuQCIu6N/J7N3Pa08olJJUMMT38K22pWdKDMcPcBe1tyayriL0wqFXstwvwr/0IuIuIDcOrwp0whGxU0PXfLUWfDXP/zYKqCPzyJuGypjKCtdJCvsCPS/SKrZLgE9KLnKvnWDPcAmxqrzzyPWxn0GiaqO0quVMQqaNjmkq5AADlozGquzNTmrKrTl2rhq8jlAEUNKLhertSX11LyTQLsiOq6rgBrcqtJqeczSZrF0PLX9CrdqQDgBxq2gyqpqTq+rF1Tghd5M4gTBsRgDLEAApdbG4UayAgK/aH7B6l006k7IG84TPQPQcCTC0/dVC0q53LdHdcI1inEf8p00G4KnUoGwTSktdMgD4aIYAIAA==&value=ETI=&code=EQehAIBUAsFNwFIGUDyA5AogEwJYBcB7AJ3BwDsBnPAQzIGN4cLxqA3anAG2oCNPGy4PHHDsiOXv3AAdYACsKsXISKzp9ApQL8AdJwIBzABQByBUvzETAGnPLiASgDcwIA==&style=ETI=&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction)

**Comment by Franciman** [comment]
Thanks @pmk65, I fixed it. I am also chasing down the origin of another error I see in the console.
When I try the schema in [this](https://rawgit.com/json-editor/json-editor/master/docs/demo.html) editor I see:
> Type error: cyclic object value

But if I try the schema in the editor you linked I don't see the error...

**Comment by pmk65** [comment]
> 
> 
> Thanks @pmk65, I fixed it. I am also chasing down the origin of another error I see in the console.
> When I try the schema in [this](https://rawgit.com/json-editor/json-editor/master/docs/demo.html) editor I see:
> 
> > Type error: cyclic object value
> 
> But if I try the schema in the editor you linked I don't see the error in the console...

That's quite odd, as it's the same version of the JSON-Editor script. 
But my playground editor creates the form in an iframe instead of injecting it on the main page.

**Comment by IanMayo** [comment]
I've been playing with the new Meta-Schema, and like it.

I'd like to explore other ways in which we can improve the support.

The `required` array is a list of items that must be present in the `properties` for that element.  Is it possible to constrain this using a $ref entry?  This _could_ result in us having drop-downs list available when recording the contents of the `required` array.

**Comment by IanMayo** [comment]
I identified a problem with the meta-schema, and reported it to @Franciman . 

The error was that the array of pets shown in the folllowing schema got implemented as an object in JSON-Editor:
````
{
"type": "object",
"properties": {
"Pets": {
"items": {
"properties": {
"Name": {
"title": "Name",
"type": "string"
},
"Age": {
"title": "Age",
"type": "number"
}
},
"title": "Pet",
"type": "object"
},
"title": "Pets",
"type": "array",
"format": "table"
}
},
"title": "Person",
"description": "Descr of person"
}
````

The issue was fixed in d6482c0

**Comment by Franciman** [comment]
I think it is ready to be reviewed now.

**Comment by pmk65** [comment]
It's says that some checks haven't been completed yet, but when you click the "details" link, the Travis tests have finished without errors.

**Comment by IanMayo** [comment]
@pmk65 - is there some step that has to be taken in order to merge the new document?

**Comment by pmk65** [comment]
> 
> 
> @pmk65 - is there some step that has to be taken in order to merge the new document?

I'm not sure if the uncompleted test message prevents the merger. but you can try making an extra commit to the PR (Doesn't have to change anything, but the commit will trigger the test again)

**Comment by IanMayo** [comment]
Thanks @pmk65 .  @Franciman - would you mind making a cosmetic change to trigger the re-test?

**Comment by schmunk42** [comment]
@pmk65 Please merge this, if you think it is ready.

**Pull request merged**
